### ISSUE TITLE
Android 8.1 arm64  app version :13.42.52  crash

### ISSUE THREAD

**Issue by ohyeah521** [wanam/YouTubeAdAway#106]
Android 8.1 arm64  app version :13.42.52  crash

**Comment by amalkorambeth** [comment]
Same here. Android 6 .arm64. youtube 13.48.52,,, YouTube crashes everytime i enable AdAway. Worked fine for few days suddenly one day it started crashing

**Comment by ohyeah521** [comment]
@amalkorambeth   @rambomhtri 
I fix it myself.

try this:

https://github.com/ohyeah521/NoAds-For-YouTube/releases
