### ISSUE TITLE
Background Playback stopped working with latest version of YouTube app

### ISSUE THREAD

**Issue by saitamasahil** [wanam/YouTubeAdAway#115]
Background Playback stopped working on Version 17.42.34. It was working perfectly on previous version.

**Comment by wanam** [comment]
@saitamasahil Could you post your xposed logs please?

**Comment by Nicolas22320** [comment]
Same issue 
[LSPosed_2022-10-28T21_45_06.648435.zip](https://github.com/wanam/YouTubeAdAway/files/9891318/LSPosed_2022-10-28T21_45_06.648435.zip)

**Comment by wanam** [comment]
@Nicolas22320 thanks for the logs, unfortunately I cannot take a look in the meantime, I'm out for 2 weeks with a limited access to my pc.

Will take a look when I come back.

**Comment by sporso** [comment]
Same problem.. log says brute force failed

**Comment by aguys123** [comment]
> @Nicolas22320 thanks for the logs, unfortunately I cannot take a look in the meantime, I'm out for 2 weeks with a limited access to my pc.
> 
> Will take a look when I come back.

Sure, take your time.

**Comment by wanam** [comment]
Closed by https://github.com/wanam/YouTubeAdAway/commit/c3d82542e05029b93201ca8facc81a67d0903b7d
