### ISSUE TITLE
Latest version of youtube app crashes when watching certain videos

### ISSUE THREAD

**Issue by aguys123** [wanam/YouTubeAdAway#118]
As the title says, it crashes on certain videos, is that weird? (for example, it crashes when I tried to watch this video https://youtu.be/3fjdXG4W_sE)

I'm on the latest beta Youtube v17.46.33. Logs attached.
[LSPosed_2022-11-18T09_08_32.926706.zip](https://github.com/wanam/YouTubeAdAway/files/10036936/LSPosed_2022-11-18T09_08_32.926706.zip)

Currently, I rolled back to v17.45.34, and everything is good again. thx

**Comment by wanam** [comment]
@aguys123 thank you for the detailed report, could you please try YouTube v17.46.32 (beta) and see if you get the same crash, I'm not able to reproduce it on both versions.

Do you have any other active modules on YouTube scope?
