### ISSUE TITLE
Adblock not working after Android Update.

### ISSUE THREAD

**Issue by Switch123456789** [wanam/YouTubeAdAway#120]
I updated Android yesterday and now adblock isn't working anymore but pip still works fine.
Device: Fairphone 3 | iodé 3 (Android12)

**Comment by Switch123456789** [comment]
Log:
`/data/app/~~UA5nz6U9AbQsKfNmjSAOtw==/ma.wanam.youtubeadaway-KfDObOwy9xpqk5HyiLAF-Q==/base.apk
[ 2022-12-06T23:58:55.939    10365:  6680:  6680 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2022-12-06T23:58:56.547    10365:  6680:  6680 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube null
[ 2022-12-06T23:58:56.735    10365:  6680:  6752 I/LSPosed-Bridge  ] Hooked bg class: aaja.m
[ 2022-12-06T23:58:56.735    10365:  6680:  6752 I/LSPosed-Bridge  ] Video BG playback hooks applied in 0 seconds!
[ 2022-12-06T23:58:57.476    10365:  6680:  6752 I/LSPosed-Bridge  ] Hooked ad class: abxg.e
[ 2022-12-06T23:58:57.477    10365:  6680:  6752 I/LSPosed-Bridge  ] In-Video ads hooks applied in 0 seconds!
[ 2022-12-06T23:59:15.404    10365:  8577:  8577 I/LSPosed-Bridge  ] Loading module ma.wanam.youtubeadaway from /data/app/~~UA5nz6U9AbQsKfNmjSAOtw==/ma.wanam.youtubeadaway-KfDObOwy9xpqk5HyiLAF-Q==/base.apk
[ 2022-12-06T23:59:15.408    10365:  8577:  8577 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2022-12-06T23:59:15.900    10365:  8577:  8577 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube null
[ 2022-12-06T23:59:16.072    10365:  8577:  8612 I/LSPosed-Bridge  ] Hooked bg class: aaja.m
[ 2022-12-06T23:59:16.072    10365:  8577:  8612 I/LSPosed-Bridge  ] Video BG playback hooks applied in 0 seconds!
[ 2022-12-06T23:59:16.903    10365:  8577:  8612 I/LSPosed-Bridge  ] Hooked ad class: abxg.e
[ 2022-12-06T23:59:16.904    10365:  8577:  8612 I/LSPosed-Bridge  ] In-Video ads hooks applied in 0 seconds!

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd maybe crashed (err=No such file or directory), retrying in 1s...

Logd crashed too many times, trying manually start...
[ 2022-12-07T00:00:19.770    10365: 10452: 10452 I/LSPosed-Bridge  ] Loading module ma.wanam.youtubeadaway from /data/app/~~UA5nz6U9AbQsKfNmjSAOtw==/ma.wanam.youtubeadaway-KfDObOwy9xpqk5HyiLAF-Q==/base.apk
[ 2022-12-07T00:00:19.774    10365: 10452: 10452 I/LSPosed-Bridge  ]   Loading class ma.wanam.youtubeadaway.Xposed
[ 2022-12-07T00:00:19.922    10365: 10452: 10452 I/LSPosed-Bridge  ] Hooking YouTube version: com.google.android.youtube null
[ 2022-12-07T00:00:20.035    10365: 10452: 10478 I/LSPosed-Bridge  ] Hooked bg class: aaja.m
[ 2022-12-07T00:00:20.036    10365: 10452: 10478 I/LSPosed-Bridge  ] Video BG playback hooks applied in 0 seconds!
[ 2022-12-07T00:00:20.696    10365: 10452: 10478 I/LSPosed-Bridge  ] Hooked ad class: abxg.e
[ 2022-12-07T00:00:20.696    10365: 10452: 10478 I/LSPosed-Bridge  ] In-Video ads hooks applied in 0 seconds!`

**Comment by wanam** [comment]
@Switch123456789 Thanks for the logs, are you using the official YouTube app?
What version of YouTube are you using?

**Comment by Switch123456789** [comment]
For some reason auto-updates has been disabled in play store so I was on an outdated version. With the latest one it is working fine again, I am a bit confused about how an Android-update can break compatibility between specific module-features and specific YouTube-versions. I would've checked that otherwise. Thank you :) and sorry for this rather unnecessary report. I will reopen the issue if it turns out to be a fluke but I am sure it's fine now.

**Comment by Switch123456789** [comment]
Update: Today I did another Android-update and the exact same thing happened, Youtube was up to date this time. Rebooting Android a second time solved it this time (pip was working again but slightly broken, I couldn't resize the window).
