### ISSUE TITLE
Adding option to enable or disable popup playback

### ISSUE THREAD

**Issue by mohamedraesa** [wanam/YouTubeAdAway#121]
Adding option to enable or disable popup playback will be a good idea

When no video playing and go home screen black popup video appear

**Comment by wanam** [comment]
@mohamedraesa This is not expected, can you reproduce this issue and share your xposed logs to see if there are any errors?

**Comment by mohamedraesa** [comment]
> @mohamedraesa This is not expected, can you reproduce this issue and share your xposed logs to see if there are any errors?

I mean there is no option in either YouTube nor YouTubeAdaway to disable or enable the popup video 


+ The video quality preferences not saved, you have manually to change it each time you play a video

**Comment by wanam** [comment]
Added by commit https://github.com/wanam/YouTubeAdAway/commit/cf17fd6eca4f67c8285d5d7ed75ab844df1397a2 on 5.0.6.
