### ISSUE TITLE
unable to activate.

### ISSUE THREAD

**Issue by ArekkusuMagni** [wanam/YouTubeAdAway#126]
there is no discernable way to activate the functionality. How do we activate the application?

![Screenshot_20230107_172237_YouTube AdAway_1](https://user-images.githubusercontent.com/92693232/211172540-c1ab212a-9536-43e2-99b9-9e508a7d4c45.jpg)

**Comment by Switch123456789** [comment]
1. Tap the `LSPosed`-shortcut in your launcher
2. Tap `Module`
3. Tap `YouTube AdAway`
4. Enable `enable module`
5. Check `YouTube` in the app-list

**Comment by DANISH2106** [comment]
Will it work on non rooted mobile??

**Comment by wanam** [comment]
> Will it work on non rooted mobile??

This module requires Xposed framework, if you can get Xposed framework installed without root, it should be good to go.

**Comment by wanam** [comment]
Closing this issue as the procedure of installation is provided.

If you still get any issues activating the module, post your Xposed logs.
