### ISSUE TITLE
Pressing back closes YouTube

### ISSUE THREAD

**Issue by Pandemic-XDA** [wanam/YouTubeAdAway#129]
Since i updated to the latest version and play a video and press back, it goes not to the homescreen of youtube and there is no player on my homescreen of youtube. I run latest LSposed, Magisk and A13 on my Xperia 1 iii, please look into it, thanks :)

**Comment by AryaAzharaZaini** [comment]
Me too

**Comment by Lovefish** [comment]
Me too.

**Comment by Switch123456789** [comment]
Same here. Let me know if logs are needed.
Phone: Fairphone 3
OS: iode 3.5 (A12) + PlayStore-Mod
YouTube: 18.02.34

**Comment by wanam** [comment]
Actually, I'm aware of this bug, and it was introduced on the latest update for a purpose, after adding [Ad cards removal](https://github.com/wanam/YouTubeAdAway/pull/123), "pull down to refresh" and "back to exit" features were broken.

Will see what I can do.

**Comment by Lovefish** [comment]
5.0.5 still has the problem.

**Comment by AryaAzharaZaini** [comment]
Installed the update 5.0.5 and fix the problem. But still, sometimes pressing back close the app again and not so often like in 5.0.4

**Comment by aguys123** [comment]
Honestly, no ads in video and background play features are enough for me.
I'm OK with Ad cards.

**Comment by wanam** [comment]
@aguys123 I agree, that's why I'm considering making the "ad cards removal" optional.

**Comment by wanam** [comment]
I added app settings to make "ad cards removal" and "background play back" optional on 5.0.6.

**Comment by Lovefish** [comment]
> 

I turned off "ad cards removal", but the problem still there

**Comment by QQ-War** [comment]
Yes, still have the problem

**Comment by wanam** [comment]
I found the culprit, thanks for reporting.
Will fix it soon.

**Comment by wanam** [comment]
Fixed on 5.0.7.
Back gesture WA is disabled when "ad cards removal" is disabled.

**Comment by Switch123456789** [comment]
Seems to be fixed for me. Thank you sir :)
