### ISSUE TITLE
Option to hide the app's icon in the launcher. 

### ISSUE THREAD

**Issue by objestik** [wanam/YouTubeAdAway#130]
Add in-app option to hide the app's icon from the launcher.

**Comment by senisditron** [comment]
Yess please add this option in next update!

**Comment by wanam** [comment]
Maybe I'm wrong but since people are asking for making some features optional, I don't see why the app needs to be hidden from the launcher.
Sorry, this won't be implemented.

**Comment by RevealedSoulEven** [comment]
Lsposed have feature of setting button by which you can make the app hidden from the homescreen and the settings can be accessed by lsposed
