### ISSUE TITLE
YouTube music issue 

### ISSUE THREAD

**Issue by Nicolas22320** [wanam/YouTubeAdAway#131]
Hi,

Last update break youtube music ( don't open) force Close

**Comment by wanam** [comment]
Hi @Nicolas22320 ,
Could you provide your xposed logs plz?

**Comment by Nicolas22320** [comment]
[Uploading LSPosed_2023-01-27T11_30_37.266437.zip…]()

**Comment by Nicolas22320** [comment]
[LSPosed_2023-01-27T11_30_37.266437.zip](https://github.com/wanam/YouTubeAdAway/files/10517925/LSPosed_2023-01-27T11_30_37.266437.zip)

**Comment by wanam** [comment]
Indeed, the 2 last updates of the module may break some of the YouTube variants (Music), I don't use them, and thus I do not test them.

You will have to stick with 5.0.3 for now until I update the application, so it safely checks the existence of "WatchWhileActivity" before trying to hooking it.

**Comment by wanam** [comment]
Fixed by commit https://github.com/wanam/YouTubeAdAway/commit/cf17fd6eca4f67c8285d5d7ed75ab844df1397a2 on 5.0.6.
