### ISSUE TITLE
Issues on new YouTube UI (18.05.34)

### ISSUE THREAD

**Issue by badbeing** [wanam/YouTubeAdAway#132]
1. Community posts under Channels' pages are falsely blocked.
![Screenshot_20230208-021154](https://user-images.githubusercontent.com/88393645/217332300-192d252e-3490-4498-b6f7-f87f0d6839b3.png)
After disabling YouTube AdAway:
![Screenshot_20230208-021241](https://user-images.githubusercontent.com/88393645/217332634-0494286f-3b79-4038-b8f8-0c10e1c2963a.png)

2. Playlists section in polished Library tab is invisible.
![Screenshot_20230208-021128](https://user-images.githubusercontent.com/88393645/217333099-4913abc6-b4a9-4cfa-94be-99d94ec76103.png)
After disabling YouTube AdAway:
![Screenshot_20230208-021227](https://user-images.githubusercontent.com/88393645/217333193-839a36d5-7b80-4c65-adf1-77afc4497d66.png)

LSPosed log: 
[LSPosed_2023-02-08T02_15_52.674086.zip](https://github.com/wanam/YouTubeAdAway/files/10678270/LSPosed_2023-02-08T02_15_52.674086.zip)
(YouTube AdAway is disabled and re-enabled several times for the above testing purposes)

**Comment by badbeing** [comment]
Tested YouTube AdAway versions: v5.04, v5.05
The aforementioned bugs are found on both versions

**Comment by wanam** [comment]
Fixed by https://github.com/wanam/YouTubeAdAway/commit/cf17fd6eca4f67c8285d5d7ed75ab844df1397a2 on 5.0.6.
