### ISSUE TITLE
Add buttons on settings

### ISSUE THREAD

**Issue by AzeAstro** [wanam/YouTubeAdAway#133]
Can you add "Disable Pop-up player" and "Disable background play" as buttons/tickboxes in YouTube app itself or inside YTAA app itself?  
I only need ad blocking and that is it. Only need background play when I listen to music but mostly I don't. Neither pop-up play.

**Comment by wanam** [comment]
Yes, it's on my to-do list.
I'm waiting to have an efficient way to use shared preferences on Xposed, it's broken on newest Android versions.

**Comment by wanam** [comment]
Added by commit https://github.com/wanam/YouTubeAdAway/commit/cf17fd6eca4f67c8285d5d7ed75ab844df1397a2 on 5.0.6.

**Comment by AzeAstro** [comment]
Great thanks!  
Both ad card remover and background play works well.
Can you do same for pop-up player option too pls?
;)))
When you disable background play, after watching video when u press home button, it uses pop-up player instead of closing completely.
