### ISSUE TITLE
oopsa: versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [wanam/YouTubeAdAway#135]
The APK attached to tag 5.0.6 shares the `versionCode` with the one from 5.0.5, maybe you forgot to increase it?

    package: name='ma.wanam.youtubeadaway' versionCode='505' versionName='5.0.6'

**Comment by wanam** [comment]
You are right, I forgot to update the `versionCode`, fortunately lsposed repo seems to push anyway

**Comment by IzzySoft** [comment]
Not sure if that's fortunate, or if a hint were better: there won't be any update notification, and Android will not consider this an update as `versionCode` was not increased. It was updated to my repo nevertheless, but installing the update will require a manual download of the APK and side-loading it with `adb install -r`; the F-Droid clients won't offer to update, because … well, I repeat myself :see_no_evil: Next release will fix that then. Thanks for checking!

**Comment by wanam** [comment]
No problems, I will push an other update with the correct version code.

**Comment by wanam** [comment]
Fixed on 5.0.7
