### ISSUE TITLE
Ad reappear again xposed log 

### ISSUE THREAD

**Issue by davex2012** [wanam/YouTubeAdAway#14]
Ad reappear again in newer YouTube version.

**Comment by davex2012** [comment]
[xposed_error_20170517_012142.txt](https://github.com/wanam/YouTubeAdAway/files/1006119/xposed_error_20170517_012142.txt)

**Comment by davedavis** [comment]
Same here. Thankfully, the card isn't as annoying as the in stream ads and the in stream ads aren't as frequent as normal. 

I think YouTube have added something that the module doesn't address. Something new. 

I wish youtube would just release youtube red globally. I'd rather just pay for this.

**Comment by Grossdm** [comment]
@davedavis Please excuse this slightly off-topic question, but what exactly is YouTube Red? I've seen their pop-ups and I dismiss them.
It looked like a subscription music service, but your comment suggests that it may be a pay for ad-free YouTube scheme.

TIA,
Doug®

**Comment by davedavis** [comment]
@Grossdm
It is indeed a paid ad free service with a few additional features. Google is giving away a free subscription to Google Music with it. 

I'd love to pay for it. The deal is great. But Google don't want to release it worldwide. Until then, I'm stuck hacking away to avoid ads because Google won't take my money. Which is madness. 

As the development of this module has ceased, I'd recommend downloading an older APK from apkmirror.com and using that with this Xposed module. It works like a charm, just turn off auto update in the play store!

**Comment by Grossdm** [comment]
Wow, thanks for the lightening fast response!

I have a couple questions.

Would a VPN allow you to use YouTube Red? 

Your suggestion to use an older version of YouTube is precisely what I've done.
I have YouTube version 12.15.55, which I think I saw in the brief release notes for this version of YouTubeAdAway as a confirmed working setup.

I'm getting ads, perhaps fewer than without the module, but do you have a setup that works perfectly?

Thanks again!

**Comment by davedavis** [comment]
Hey @GrossDM

I'm using version 11.21.53, I just randomly picked it in my search for an even older version that allowed downloading of the videos for offline viewing. I didn't have time to install more to find it. But this one is working. 

It might be worth noting that I have adaway installed too. If you don't have it, you should. It's amazing. That might have something to do with it. However, I'd try going back a bit further. 

As for the VPN, I believe you'd need an account and billing address in the US (or one of the other few supported countries) for this to work. And watching YouTube over a VPN is a nightmare even if it's your own roll your own VPN on AWS or Azure (Streisand is a good choice for this). 

Google doesn't want my money. So I'm sticking with this and adaway (needs root which you obviously have). 

Hope that helps.

**Comment by Grossdm** [comment]
I have used AdAway in the past, but for quite a while a combination of things has been working well:
1. MinMinGuard - Xposed module. If you aren't using its latest alpha, get it now. It's the best thing for blocking ads throughout Android that exists.
2. YouTubeAdAway
3. uBlock Original in Firefox. I know Chrome is faster, but I like blocked ads, privacy, and security - all antithetical to Chrome.
4. More recently, I've been using Xprivacy to thwart ads. For YouTube, I don't know which hostnames need to be blocked (some are obvious). It appears that YouTube is getting IP addresses to contact without polling DNS. Xprivacy offers to block IPv4 with a wildcard, like xxx.xxx.xxx.* but it does NOT offer this for IPv6.
The Xprivacy dev isn't interested in fixing it, as he responded to my issue on GitHub. He wants me to use his NetGuard firewall.

Sorry for the Xprivacy commentary.

If you know the hostnames to block for YouTube, please share this info! 😆

**Comment by davex2012** [comment]
Is @wanam abandoned YouTube ad?

**Comment by wanam** [comment]
@davex2012 No, but I don't have time to work on this now and I am not running a MM Rom.

**Comment by davex2012** [comment]
Ah.. Okay. 👍
