### ISSUE TITLE
[enhancement] straight into background instead of pip on going to homescreen

### ISSUE THREAD

**Issue by Ontropy** [wanam/YouTubeAdAway#144]
While a video is playing, on pressing the home button, it goes into pip. You then have to close it and then resume from notifications. This happens only when bg play is activated. When its disabled, the video just pauses but doesn't go into pip. 

I was hoping that on home button press, the video should continue playing in the notifs, sort of like how music players work.

**Comment by wanam** [comment]
This is the default YouTube behavior, and this is the easiest way to YT in pip.
The scenario you describe can be triggered with the back button.
