### ISSUE TITLE
Youtube 12.17.54 ad card 

### ISSUE THREAD

**Issue by Beastador** [wanam/YouTubeAdAway#15]
https://m.imgur.com/a/3oySG

https://i.imgur.com/qYRPMC7.png

**Comment by rambomhtri** [comment]
Yeah, what about the ad card of the newest apk versions?

Thanks

**Comment by wanam** [comment]
Is this a Kitkat Rom?

**Comment by rambomhtri** [comment]
No, it's Marshmallow 6.0.1 (vanilla), Xposed 3.1.1 SDK23 v87, SuperSU 2.82, AdAway 3.5.1, YouTube 12.21.57

**Comment by wanam** [comment]
Please try the latest update 3.6.1.

**Comment by rambomhtri** [comment]
@wanam 
Hi, after a factory reset of my device, I installed YouTube 12.34.55 and this module, and the first 2 days I got 2 ads. It's been 1 week since then and I'm not getting ads anymore, ad cards have been removed, everything is working fine, thank you very much.
