### ISSUE TITLE
Enable Background Playback no longer works on YouTube v18.27.32+

### ISSUE THREAD

**Issue by badbeing** [wanam/YouTubeAdAway#155]
Since v18.27.32, when a user turns off their phone screen the video will automatically stop playing.
Device: Pixel 7 Pro

LSPosed logs:
[LSPosed_2023-07-07T18_17_35.316819.zip](https://github.com/wanam/YouTubeAdAway/files/11980718/LSPosed_2023-07-07T18_17_35.316819.zip)

**Comment by thingo73** [comment]
That's right.  I also have the same problem on Xiaomi 11. Hope the developer will fix it soon

**Comment by wanam** [comment]
@badbeing according to your logs, the background patch seems to hook the correct class but the wrong method, unfortunately, I cannot help in the meanwhile, I won't be near my PC for the upcoming 4 weeks
I will take a look at it when I come back from vacation...

**Comment by badbeing** [comment]
No worries, I've downgraded to a slightly older version since the module works perfectly fine there. Enjoy your vacation! 😄

**Comment by AllenChangMusic** [comment]
FYI, it started working for me again on version 18.28.33!
Not sure if they unintentionally broke something and fixed it.

**Comment by psychopathologist** [comment]
> @badbeing according to your logs, the background patch seems to hook the correct class but the wrong method, unfortunately, I cannot help in the meanwhile, I won't be near my PC for the upcoming 4 weeks I will take a look at it when I come back from vacation...

First, enjoy your vacation!

In your code, the findAndHookVideoBGP4C method is hooking on a wrong class (adun), the correct one would be acxn. I've messed around with this here for a while, and I've been able to verify that the such class has always no declared fields, so adding one more check to the code (below) did the trick here. Ofce you'll check and write something more elegant to handle with that!

if (aClass.getDeclaredFields().length > 1) return false;

**Comment by badbeing** [comment]
I got tagged again by the previous comment lol. Anyway, just a small PSA that I have unrooted my device, so I no longer have access to any Xposed modules (especially the YouTube app is a system app on Pixels) and so I cannot perform any testing. 😔

**Comment by wanam** [comment]
I tried the module today, and it seems to work fine against the latest YouTube version 18.34.37 I see on the Play Store.
Maybe it was related to some YouTube app changes that were discarded after 18.28.33 like @AllenChangMusic said in a previous comment https://github.com/wanam/YouTubeAdAway/issues/155#issuecomment-1637084919
