### ISSUE TITLE
youtube minimizes when clicked back button while watching videos

### ISSUE THREAD

**Issue by gengooro** [wanam/YouTubeAdAway#159]
When click back button while playing videos on YouTube, instead of minimising the video the whole youtube app minimizes..

thought that youtube has bug, but when disabled the YoutubeAdAway, everything works fine, so the bug is in the YoutubeAdAway..

**Comment by wanam** [comment]
This is related to the hide cards feature which is an experimental patch (duplicate of https://github.com/wanam/YouTubeAdAway/issues/129).
