### ISSUE TITLE
Ads are completely back

### ISSUE THREAD

**Issue by NewRaGu** [wanam/YouTubeAdAway#16]
Hello Sir/Madam, 

Ads started coming from last few days. Installation of previous version of the YouTube app didn't help either. Kindly update your database.

**Comment by Grossdm** [comment]
Have you made a donation to wanam to help his efforts toward blocking ads?
I'm sure that would be helpful, and certainly appreciated.

**Comment by davedavis** [comment]
@NewRagu
Try installing a version from 2016. It's working for me. The only thing missing is the double tap to skip 10 seconds. 

Unintelligible YouTube completely, download from apkmirror.com and turn off auto update. It works great for me. I think the dev is done with this module. I wouldn't expect more donations will change his mind (although I'd happily donate if I'm wrong).

**Comment by DOASalesman** [comment]
Excuse me for my naivety,  but couldn't this have something to do with the recent changes to YouTube's version numbering?

**Comment by NewRaGu** [comment]
@davedavis, The ads are blocked on YouTube app version 12.12.53 and lower.

**Comment by NewRaGu** [comment]
@Grossdm, Yes I didn't as it has PayPal option only and PayPal has little issue with Indian debit cards. I would love to donate if he provides Paytm or something like this payment system either.

**Comment by NewRaGu** [comment]
@DOASalesman, Yes I have the same question.

**Comment by Grossdm** [comment]
@NewRaGu, where did you get the info on **YouTube** v. 12.12.53 as the latest version that is controlled by this module?

BTW, I'll just mention that for **YouTube AdAway** v. 3.5.1 the "Changes:" state "Support YouTube 12.15.x."
Mind you, I'm not suggesting that 12.15.x does work.  I've been using **YouTube** v. 12.15.55 and it does not work.  In fact, a day or two ago I spent some quality time on [APKmirror.com](http://www.apkmirror.com/) downloading older versions sequentially with the obvious plan to empirically determine what you apparently already know.

Oh ya, **_thank you_** for this info!

**Comment by davedavis** [comment]
If anyone is making their way back through YouTube versions on apkmirror, there's a version of the YouTube app that has the offline viewing/download feature enabled by this module. 

I can't seem to find it. It was around August 2016. If you find it, please let me know. It was the best version of YouTube and I believe released by mistake by Google. And of course, has zero ads with this module. 

Would also be good to get a definitive final version that this module is compatible with.

**Comment by rambomhtri** [comment]
I'm using latest 12.21.57 YouTube app and this module still works just fine, except for the ad cards. I got an ad yesterday though, but it hasn't happened again since yesterday.

**Comment by froggz19** [comment]
The last version I had was 12.15.55 and it worked great with that so I switched back to it.

**Comment by Grossdm** [comment]
Thanks @froggz19.
I didn't know that the ad cards were to be tolerated - I had assumed that if this module didn't block all ads, then the YouTube app had changed enough that it wouldn't block any ads.

I'm now using 12.15.55 as well, and I only get the ad cards. No forced watching of video ads, thankfully.

**Comment by froggz19** [comment]
@Grossdm you shouldn't get the ad cards, have you tried to delete the app cache and data?

**Comment by rambomhtri** [comment]
@froggz19 You shouldn't get the ad cards IF your YouTube app version is like 2 months old. All the newer versions of the app include this new "feature" of ad cards, and this module can't get rid of them.

**Comment by NewRaGu** [comment]
Do something @wanam

**Comment by davedavis** [comment]
@NewRaGu
I think it's safe to say that development is dead. 

Either downgrade your app version to resolve the issue or move to Magisk.

**Comment by NewRaGu** [comment]
@davedavis, Yeah it seems the developer is no more interested in developing the app. BTW he can also make a donation version of this app to get it work as advertised. I'm ready to pay.

**Comment by NewRaGu** [comment]
No the development hasn't been abandoned yet as I got a new update v3.5.3 and it seems the ads will not reappear at least upto the current YouTube app versions. Thanks @wanam sir.

**Comment by NewRaGu** [comment]
Update: 1
@wanam sir, I got an ad. Just one by now.

**Comment by NewRaGu** [comment]
Update: 2
@wanam sir, ads started reappearing.
