### ISSUE TITLE
Module doesn't work anymore

### ISSUE THREAD

**Issue by duongden** [wanam/YouTubeAdAway#160]
Youtube updated and this module doesn't work anymore

My Youtube version: 18.36.38

[log.zip](https://github.com/wanam/YouTubeAdAway/files/12609432/log.zip)

**Comment by bulkatoz** [comment]
Don't working the background play in the versión 18.36.38 please update

**Comment by Tomorrowisgoodya** [comment]
18.36.38 Same

**Comment by Pandemic-XDA** [comment]
Any fix or update ?

**Comment by wanam** [comment]
YouTube Support to 18.36+ on the new module version 5.1.0.
If it does not show yet on LSXposed, feel free to get it from my Github repo release page.
