### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by JJ-Coffee** [wanam/YouTubeAdAway#161]
Crash for YouTube v18.36.38

**Comment by Pandemic-XDA** [comment]
Yes same here on A13

**Comment by geekcanion** [comment]
Crash it and it doesn't play videos in the background, however you can watch ad-free videos on YouTube but the app crashes constantly (version 18.36.39)

**Comment by wanam** [comment]
YouTube Support to 18.36+ on the new module version 5.1.0.
If it does not show yet on LSXposed, feel free to get it from my Github repo release page.

**Comment by Tomorrowisgoodya** [comment]
5.1.0 Perfect works, Thank you very much !

**Comment by geekcanion** [comment]
Thank you @wanam , recent update works perfectly
