### ISSUE TITLE
Is this module totally abandoned?

### ISSUE THREAD

**Issue by rambomhtri** [wanam/YouTubeAdAway#17]
Hello, I'm using latest YouTube app 12.21.57 and today a "skip ad" appeared. I've been more than a year using AdAway and this is the first time an ad passed the module filter. Also, there are now these new "ad cards" below the video that the module does not recognize as ad.

Since March there hasn't been any updates,so I wanted to know if the developer still is working on this module or not.

Thank you.

**Comment by rambomhtri** [comment]
Oh, I wanted to know also if there's an alternative to this module. I know there are modified apk, but I'm looking for something like this, an add-on that works with the official app from the Play Store.

**Comment by wanam** [comment]
No it's not abandoned, but i cannot give any ETA, the module seems to work for most of the users including on my wife's device, so unless i find something i can reproduce, there is nothing to fix on my side.

The main reason of open sourcing this module was to help you figure it out yourself (or any dev) whenever you get an ad i cannot reproduce.

**Comment by NewRaGu** [comment]
It seems @wanam has abandoned development as the app hasn't been updated for months. And even ads are completely back.

**Comment by Grossdm** [comment]
That seems strange that @wanam dropped in a comment that it's not abandoned.
Has no one presented an ad that he can reproduce? Surely there are so many that this could be done easily.
Are no other devs interested in working on the module?

**Comment by NewRaGu** [comment]
No the development hasn't been abandoned yet as I got a new update v3.5.3 and it seems the ads will not reappear at least upto the current YouTube app versions. Thanks @wanam sir.

**Comment by NewRaGu** [comment]
Update: 1
@wanam sir, I got an ad. Just one by now.

**Comment by NewRaGu** [comment]
Update: 2
@wanam sir, ads started reappearing.
