### ISSUE TITLE
Unable to remove offline video

### ISSUE THREAD

**Issue by sangalaviral** [wanam/YouTubeAdAway#18]
Since last update  I am unable to remove the offline videos. Only way is either disable this module or clear the app data.

**Comment by Fatal-Errol** [comment]
I can confirm that this is a problem. I'm on Marshmallow with the latest version of youtube.

**Comment by wanam** [comment]
Please try with 3.6.1 and post a full logcat.

**Comment by wanam** [comment]
No feedback, closing this issue.
Feel free to re-open it and post a logcat please.
