### ISSUE TITLE
Ads are back in YT 12.23.60

### ISSUE THREAD

**Issue by rambomhtri** [wanam/YouTubeAdAway#20]
I'm getting plenty of ads all of a sudden, it all started yesterday. What happened?

Now it's not only the ad cards, I'm getting regular video ads, 20 seconds with no option to skip.

**Comment by FuzzyFoxe** [comment]
I had the same thing happen on the custom apk as well, I had to roll back a version. Youtube is really getting violent about people blocking ads, damn.

**Comment by rambomhtri** [comment]
Woha, with the new update, ad cards are hidden, and I guess ads won't bug us anymore. Amazing!
