### ISSUE TITLE
ads back

### ISSUE THREAD

**Issue by rigaz29** [wanam/YouTubeAdAway#21]
Version : 12.27.53
https://cdn.pbrd.co/images/GBQ7bkp.jpg

**Comment by NewRaGu** [comment]
Yes ads are completely back.

**Comment by NewRaGu** [comment]
I got a new update v3.5.3 and it seems the ads will not reappear at least upto the current YouTube app versions. Thanks @wanam sir.

**Comment by NewRaGu** [comment]
Update: 1
@wanam sir, I got an ad. Just one by now.

**Comment by NewRaGu** [comment]
Update: 2
@wanam sir, ads started reappearing.

**Comment by rambomhtri** [comment]
Not for me, now even ad cards are gone (hidden). Working just fine.

**Comment by NewRaGu** [comment]
@rambomhtri, Sadly I see short video ads. BTW search "Mark Zuckerberg" on YouTube and watch the most viewed videos and then confirm whether you see ads or not.

**Comment by rambomhtri** [comment]
@NewRaGu Nope, not a single ad showed up. I've recorded the screen, but it's 40MB and I'm not at home right now, and I'm kind of lazy to upload it. Nonetheless, if you don't believe me, I can upload it later so you can see I did what you said and all ads were gone, including ad cards.

**Comment by NewRaGu** [comment]
@rambomhtri, Lucky you! However I'm still getting ads. As soon as I switch back to YouTube app version 12.12.53, I see no ads. What's the issue?

**Comment by rambomhtri** [comment]
I don't know, this is what I'm using:
YouTube 12.27.53
Android 6.0.1
Xposed 3.1.1
AdAway 3.5.3

**Comment by NewRaGu** [comment]
@rambomhtri, Same here on Redmi Note 3 Pro.

**Comment by rambomhtri** [comment]
Then... May be reinstall YouTube, deleting data, I don't know...

**Comment by NewRaGu** [comment]
Nothing helped. BTW I found OGYouTube on web and it's way better than official one. 

https://www.official-plus.com/ogyoutube

**Comment by NewRaGu** [comment]
@rambomhtri, Nothing helped. BTW I found OGYouTube on web and it's way better than official one. 

https://www.official-plus.com/ogyoutube
