### ISSUE TITLE
White space where ad cards below video used to be

### ISSUE THREAD

**Issue by Lightfire228** [wanam/YouTubeAdAway#25]
As the title says, there is a blank space where the ads used to be below videos.

I know this is petty and might not be something you can fix with Xposed.  Just letting you know.

![screenshot_20170803-154549](https://user-images.githubusercontent.com/15241322/28940712-9fa44250-7863-11e7-8ed8-c787eaeef96d.png)

**Comment by wanam** [comment]
Wipe your YT app data and try again.

**Comment by Lightfire228** [comment]
Still there after data wipe and soft reboot

I forgot the debug details:
Nexus 6p
Stock android 6.0.1 MTC20L
Traditional Root, SuperSu binary
Xposed 87
Xposed modules:
    Youtube Adaway 3.5.3
    Youtube background playback 2.0.4
    others not YT related

**Comment by Lightfire228** [comment]
Closing because this is a non-issue.

**Comment by wanam** [comment]
Actually it is an issue, i just don't have any workaround for it right now, the ad layout is being hidden correctly, but YouTube manipulate the ad layout parent after inflating the layout and sets it's height to a fixed value.

**Comment by Lightfire228** [comment]
Sorry, I figured devs get tired of not closed issues. Didn't think you'd actually want to fix it, since it's just a petty layout issue

**Comment by wanam** [comment]
Fixed with the new implementation on 4.1.0.
