### ISSUE TITLE
Ads appearing in most recent version on tested apk

### ISSUE THREAD

**Issue by fyaasko** [wanam/YouTubeAdAway#28]
So when viewing popular videos i get your basic video ads, frustrating. One that always dispenses an ad after i've reinstalled is OfficialPsy's new Love music video. Here's a log?

09-04 14:58:44.058 I/Xposed  (17641): YouTube: com.google.android.youtube 12.32.60 loaded!
09-04 14:59:11.600 I/Xposed  (17641): YouTube AdAway: Successfully hooked ads DB wce
09-04 14:59:31.633 I/Xposed  (17641): YouTube AdAway: Successfully hooked ads fetchers

:< it does Feel like i'm getting less ads, but i'm still getting them, does anyone know of a workin apk and adaway version combo?

**Comment by Bigdogmacho** [comment]
09-06 07:24:30.874 I/Xposed  (  847): -----------------
09-06 07:24:30.874 I/Xposed  (  847): Starting Xposed version 86, compiled for SDK 22
09-06 07:24:30.874 I/Xposed  (  847): Device: SM-N910T (samsung), Android version 5.1.1 (SDK 22)
09-06 07:24:30.874 I/Xposed  (  847): ROM: cm_trltetmo-userdebug 5.1.1 LMY48Y d9713e640d test-keys
09-06 07:24:30.874 I/Xposed  (  847): Build fingerprint: samsung/trltetmo/trltetmo:5.0.2/LRX22G/N910TUVU1ANIH:user/release-keys
09-06 07:24:30.874 I/Xposed  (  847): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-06 07:24:30.874 I/Xposed  (  847): SELinux enabled: yes, enforcing: yes
09-06 07:24:30.880 I/Xposed  (  847): -----------------
09-06 07:24:30.880 I/Xposed  (  847): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-06 07:24:30.991 I/Xposed  (  847): Detected ART runtime
09-06 07:24:30.992 I/Xposed  (  847): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-06 07:24:31.079 I/Xposed  (  847): Loading modules from /data/app/com.oasisfeng.greenify-1/base.apk
09-06 07:24:31.765 I/Xposed  (  847):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
09-06 07:24:31.775 I/Xposed  (  847):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
09-06 07:24:31.776 I/Xposed  (  847): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
09-06 07:24:31.786 I/Xposed  (  847):   Loading class ma.wanam.youtubeadaway.Xposed
09-06 07:24:31.788 I/Xposed  (  847):   Loading class ma.wanam.youtubeadaway.ResXposed
09-06 07:25:35.450 W/Xposed  ( 2668): Package name for /system/priv-app/Dialer/Dialer.apk had to be retrieved via parser
09-06 07:25:35.491 W/Xposed  ( 2668): Package name for /system/app/Camera2/Camera2.apk had to be retrieved via parser
09-06 07:25:38.004 W/Xposed  ( 2668): Package name for /system/priv-app/SystemUI/SystemUI.apk had to be retrieved via parser
09-06 07:25:54.294 I/Xposed  ( 4926): YouTube: com.google.android.youtube 12.32.60 loaded!
09-06 07:25:57.088 I/Xposed  ( 4926): YouTube AdAway: Successfully hooked ads DB wce
09-06 07:26:03.202 I/Xposed  ( 4926): YouTube AdAway: Successfully hooked ads fetchers
09-06 07:27:19.322 I/Xposed  ( 6190): YouTube: com.google.android.youtube 12.32.60 loaded!
09-06 07:27:21.824 I/Xposed  ( 6190): YouTube AdAway: Successfully hooked ads DB wce
09-06 07:27:26.412 I/Xposed  ( 6190): YouTube AdAway: Successfully hooked ads fetchers

**Comment by jwagra** [comment]
the latest version - 12.34.54 (http://www.androidapksfree.com/apk/youtube-apk-latest-version-download/)

**Comment by Bigdogmacho** [comment]
FWIW, version 3.6.0 of YouTube Ad Away seems to not block ads on YouTube version 12.12.53 which I believe is the last known version to be fully functional with YouTube Ad Away version 3.5.3. I have not tried the version posted by @jwagra being that Dev said latest version of YouTube Ad Away was tested against 12.32.60.

**Comment by RobQ** [comment]
Same here, version 3.6.0 shows ads even in the old YouTube version 12.12.53.  3.5.3 does not.

I also saw ads in YT 12.21.57 and 12.15.55, two versions mentioned in other reports.
