### ISSUE TITLE
Major issue

### ISSUE THREAD

**Issue by coolNAO** [wanam/YouTubeAdAway#29]
Not updating the YouTube app doesn't prevent new advertising. I think new advertising and advertising framework is pushed through updates to Google Play Services and unfortunately Google Play Services automatically updates and you can't disable it. This new advertisement is for YouTube red. Perhaps add a feature to toggle the automatic updates to Google play services? Idk I could be wrong but that's my most logical guess for the reason for new ads. And yes I've tried clearing app data and rebooting. This makes me want to kill Google employees. Below is the image link to the ad.
https://ibb.co/fUY5ya
09-06 09:46:46.502 I/Xposed  (  430): -----------------
09-06 09:46:46.502 I/Xposed  (  430): Starting Xposed version 87, compiled for SDK 22
09-06 09:46:46.502 I/Xposed  (  430): Device: XT1254 (motorola), Android version 5.1 (SDK 22)
09-06 09:46:46.502 I/Xposed  (  430): ROM: SU4TL-44
09-06 09:46:46.502 I/Xposed  (  430): Build fingerprint: motorola/quark_verizon/quark:5.1/SU4TL-44/44:user/release-keys
09-06 09:46:46.502 I/Xposed  (  430): Platform: armeabi-v7a, 32-bit binary, system server: yes
09-06 09:46:46.502 I/Xposed  (  430): SELinux enabled: yes, enforcing: yes
09-06 09:46:49.320 I/Xposed  (  430): -----------------
09-06 09:46:49.320 I/Xposed  (  430): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-06 09:46:49.429 I/Xposed  (  430): Detected ART runtime
09-06 09:46:49.432 I/Xposed  (  430): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-06 09:46:49.583 I/Xposed  (  430): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
09-06 09:46:49.589 I/Xposed  (  430):   Loading class ma.wanam.youtubeadaway.Xposed
09-06 09:46:49.593 I/Xposed  (  430):   Loading class ma.wanam.youtubeadaway.ResXposed
09-06 09:47:52.184 I/Xposed  ( 4890): YouTube: com.google.android.youtube 11.49.55 loaded!
09-06 09:47:58.183 I/Xposed  ( 4890): YouTube AdAway: Successfully hooked ads DB sna
09-06 09:48:04.819 I/Xposed  ( 4890): YouTube AdAway: Successfully hooked ads fetchers
09-06 09:49:41.522 I/Xposed  ( 9783): YouTube: com.google.android.youtube 11.49.55 loaded!
09-06 09:49:44.755 I/Xposed  ( 9783): YouTube AdAway: Successfully hooked ads DB sna
09-06 09:49:49.153 I/Xposed  ( 9783): YouTube AdAway: Successfully hooked ads fetchers

**Comment by coolNAO** [comment]
also you can reproduce the ad by going to any music Playlist on YouTube with more than 5 songs, play the Playlist and skip to the next video a few times.

**Comment by coolNAO** [comment]
and I'm not sure if finding a way to disable updates to Google Play Services is a great idea for a solution to this issue because if it stays outdated for too long I've heard it can cause compatibility issues with new or updated Google apps

**Comment by fyaasko** [comment]
I'm having the same troubles, regardless of versions or methods I try, my youtube app is now displaying ads as of this morning, yesterday everything was fine and dandy.

Totally willing to pay for this shit to stop, worst mood kill ever to be listening to meaningful music and have it cut out with ENJOY A BURGER.

Not sure why these threads are just being closed
