### ISSUE TITLE
Ads are back in YouTube 

### ISSUE THREAD

**Issue by Bigdogmacho** [wanam/YouTubeAdAway#3]
03-22 13:41:32.184 I/Xposed  (  341): -----------------
03-22 13:41:32.184 I/Xposed  (  341): Starting Xposed version 86, compiled for SDK 22
03-22 13:41:32.184 I/Xposed  (  341): Device: SM-N910T (samsung), Android version 5.1.1 (SDK 22)
03-22 13:41:32.184 I/Xposed  (  341): ROM: cm_trltetmo-userdebug 5.1.1 LMY48Y d9713e640d test-keys
03-22 13:41:32.184 I/Xposed  (  341): Build fingerprint: samsung/trltetmo/trltetmo:5.0.2/LRX22G/N910TUVU1ANIH:user/release-keys
03-22 13:41:32.184 I/Xposed  (  341): Platform: armeabi-v7a, 32-bit binary, system server: yes
03-22 13:41:32.184 I/Xposed  (  341): SELinux enabled: yes, enforcing: yes
03-22 13:41:32.195 I/Xposed  (  341): -----------------
03-22 13:41:32.195 I/Xposed  (  341): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-22 13:41:32.566 I/Xposed  (  341): Detected ART runtime
03-22 13:41:32.572 I/Xposed  (  341): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-22 13:41:32.851 I/Xposed  (  341): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
03-22 13:41:32.995 I/Xposed  (  341):   Loading class ma.wanam.youtubeadaway.Xposed
03-22 13:42:28.885 W/Xposed  ( 3474): Package name for /system/priv-app/Dialer/Dialer.apk had to be retrieved via parser
03-22 13:42:29.040 W/Xposed  ( 3474): Package name for /system/app/Camera2/Camera2.apk had to be retrieved via parser
03-22 13:42:33.590 I/Xposed  ( 4283): YouTube: com.google.android.youtube 12.09.58 loaded!
03-22 13:42:33.610 I/Xposed  ( 4283): YouTube AdAway 3.5.0: Trying brute force way...
03-22 13:42:35.297 W/Xposed  ( 3474): Package name for /system/priv-app/SystemUI/SystemUI.apk had to be retrieved via parser
03-22 13:42:48.563 I/Xposed  ( 4283): YouTube AdAway: Successfully hooked ads DB: tig
03-22 13:42:52.513 I/Xposed  ( 4283): YouTube AdAway: Successfully hooked pkw constructor!
03-22 13:42:52.516 I/Xposed  ( 4283): YouTube AdAway: Successfully hooked pkw param=nps
03-22 13:42:55.085 I/Xposed  ( 4283): YouTube AdAway: Successfully hooked ad response: mbi

Hope I did this correctly.

**Comment by wanam** [comment]
Same as https://github.com/wanam/YouTubeAdAway/issues/1
