### ISSUE TITLE
Ads when you open a youtube video through external link

### ISSUE THREAD

**Issue by malitech** [wanam/YouTubeAdAway#30]
If I click on a youtube link from chrome for example and when it takes me to the youtube app, I get ads. There is nothing in the logs.

**Comment by wanam** [comment]
You mean you are getting in-video ads only on this case?
Please try to reproduce it with the latest update and post a screenshot with your xposed logs?

**Comment by malitech** [comment]
Yes, exactly. Only if another app takes me to youtube. I've just checked with chrome.
Logs don't have anything useful, just "Successfully hooked ads wrapper, fetchers..."

**Comment by wanam** [comment]
Should be fixed on 4.1.0.
