### ISSUE TITLE
Amazon Ad with Youtube 12.39.60

### ISSUE THREAD

**Issue by sutobe** [wanam/YouTubeAdAway#31]
Hello,

since ~2 days I am getting an ad from Amazon when I want to watch the first video after opening Youtube.

HTC 10, Nougat 7.0, Rooted, Xposed v88.1.

Using Youtube Adaway module.

Also having MinMinGuard and Adaway app running, both of them also can't make the Amazon ad stop showing.

I cleared Youtube Cache and Data, turned off every other module in Xposed and saved the logfile as mentioned in your (Wanam's) initial post in the xda forums.

Also tried protocolling the DNS requests with Adaway but it didn't give me any good results, meaning I have no idea which might've been the Amazon ad.

I made a couple of screenshots, also here's the xposed log

Is there anything else you need?

Cheers

> 10-13 12:42:28.207 I/Xposed  (  976): -----------------
10-13 12:42:28.207 I/Xposed  (  976): Starting Xposed version 88.1, compiled for SDK 24
10-13 12:42:28.207 I/Xposed  (  976): Device: HTC 10 (HTC), Android version 7.0 (SDK 24)
10-13 12:42:28.207 I/Xposed  (  976): ROM: NRD90M release-keys
10-13 12:42:28.207 I/Xposed  (  976): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:7.0/NRD90M/857212.41:user/release-keys
10-13 12:42:28.207 I/Xposed  (  976): Platform: arm64-v8a, 64-bit binary, system server: yes
10-13 12:42:28.207 I/Xposed  (  976): SELinux enabled: yes, enforcing: yes
10-13 12:42:28.264 I/Xposed  (  976): -----------------
10-13 12:42:28.264 I/Xposed  (  976): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-13 12:42:29.496 I/Xposed  (  976): Detected ART runtime
10-13 12:42:29.513 I/Xposed  (  976): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-13 12:42:30.550 I/Xposed  (  976): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
10-13 12:42:30.565 I/Xposed  (  976):   Loading class ma.wanam.youtubeadaway.Xposed
10-13 12:42:30.566 I/Xposed  (  976):   Loading class ma.wanam.youtubeadaway.ResXposed
10-13 12:42:38.349 I/Xposed  (  990): -----------------
10-13 12:42:38.349 I/Xposed  (  990): Starting Xposed version 88.1, compiled for SDK 24
10-13 12:42:38.349 I/Xposed  (  990): Device: HTC 10 (HTC), Android version 7.0 (SDK 24)
10-13 12:42:38.349 I/Xposed  (  990): ROM: NRD90M release-keys
10-13 12:42:38.349 I/Xposed  (  990): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:7.0/NRD90M/857212.41:user/release-keys
10-13 12:42:38.349 I/Xposed  (  990): Platform: arm64-v8a, 32-bit binary, system server: no
10-13 12:42:38.350 I/Xposed  (  990): SELinux enabled: yes, enforcing: yes
10-13 12:42:38.359 I/Xposed  (  990): -----------------
10-13 12:42:38.359 I/Xposed  (  990): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
10-13 12:42:38.937 I/Xposed  (  990): Detected ART runtime
10-13 12:42:38.953 I/Xposed  (  990): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
10-13 12:42:39.897 I/Xposed  (  990): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
10-13 12:42:39.910 I/Xposed  (  990):   Loading class ma.wanam.youtubeadaway.Xposed
10-13 12:42:39.911 I/Xposed  (  990):   Loading class ma.wanam.youtubeadaway.ResXposed

![screenshot_20171013-124432](https://user-images.githubusercontent.com/32777366/31558268-83b4701c-b04c-11e7-91c7-0712e751a702.png)
![screenshot_20171013-124441](https://user-images.githubusercontent.com/32777366/31558276-8bf63602-b04c-11e7-9c02-e6301dfcb9b7.png)
![screenshot_20171013-124511](https://user-images.githubusercontent.com/32777366/31558289-9707fc74-b04c-11e7-9c08-ec9befe69baf.png)
![screenshot_20171013-124523](https://user-images.githubusercontent.com/32777366/31558300-a2103cee-b04c-11e7-85c5-03e91ac4a5a8.png)
![screenshot_20171013-124659](https://user-images.githubusercontent.com/32777366/31558310-a6d61fbe-b04c-11e7-937f-9f274e3488c7.png)
![screenshot_20171013-124853](https://user-images.githubusercontent.com/32777366/31558316-aaee5990-b04c-11e7-97dc-8dec91fe022c.png)
![screenshot_20171013-124901](https://user-images.githubusercontent.com/32777366/31558325-afeea80a-b04c-11e7-8700-a9a45a8aff5e.png)
![screenshot_20171013-125132](https://user-images.githubusercontent.com/32777366/31558330-b6279650-b04c-11e7-9579-59765415b27d.png)

**Comment by Nergal-di-Cuthah** [comment]
Try the youtube listed in changelog (12.32.60) see if it blocks the ad

**Comment by sutobe** [comment]
I had no ads in 12.32.60

**Comment by Nergal-di-Cuthah** [comment]
There's your answer then :)

**Comment by sutobe** [comment]
so this means I don't have to report new ads and I can expect an update?

cheers

**Comment by malitech** [comment]
I have the same issue in the latest version 12.39.60

**Comment by sutobe** [comment]
I rolled back to 12.32.60 now I am gettin ads there as well.
My brother (same phone as I, HTC 10 7.0 v88.1 xposed adblock, youtube adblock, no minminguard but adblock reborn which does nothing on my phone) has no issues whatsoever and is on the latest youtube app.
I cleared caches, cleared data, cleared play and search history, cleared android/data/youtube folders. Nothing.

The only thin that seems to work is logging out from my youtube account on the phone!
My brother doesnt need to do that.
Why isnt he getting ads but I do? 
Wer're on the same Wifi as well (doesnt matter tbh)

**Comment by 29988122** [comment]
I can confirm that I also start getting ads even with 12.32.60

It said successfully hooked, but still got ads. 
https://pastebin.com/NCW7gxHP

Thanks for keep updating!

**Comment by tyteen4a03** [comment]
Can confirm ads on 12.32.60 as well on Galaxy S7 Edge Helios v7.23.1 w/ Xposed Systemless. Logs are available if necessary.

**Comment by gmipf** [comment]
I can confirm, since today i get the Amazon ad. Until today everything was ok. Youtube App is v12.42.59

**Comment by wanam** [comment]
Sorry for late reply, busy with real life.
@sutobe your logs seems incomplete, i don't see the hooks messages, did you disable the module logs?
@29988122 Please try the new update of the module 3.7.0, with no other Youtube modules (name.mikanoshi.yourtubeplus), to make sure it's not interfering.
@gmipf Please post a screenshot of the ad if you can reproduce it, and post your xposed logs.

Rolling back to older YouTube versions won't help much, please keep reporting issues against the latest update of the module and YT app.

I also pushed the latest version of my sources, feel free to contribute if you can debug those ads.

**Comment by sutobe** [comment]
Thanks for your reply and the update.
Can you describe how I can perform a logging process with all the information you need?

Meanwhile I tested the module update with the same YOutube Version you have.

Gog a Domino's Pizza ad before the clip would play so I guess the update isn't entirely working.

**Comment by sutobe** [comment]
Now a clip of Star Wars BF2 Gameplay wouldn't start with the module turned on, this is the link to the video    https://youtu.be/AQRMMuBBPVo

Videos related to Star Wars seem to be more likely to get an ad before the video will start since I rarely get ads with videos that have nothing to do with SW. Didn't pay attention if this is happening more often on certain channels tbh.

Then I had a "watch now" suggestion in a video which came back at a certain point in the video, so I could skip back and it would show every time. Not sure but I think Youtube Adaway was able to stop those suggestions to show, am I right?

![screenshot_20171111-220709](https://user-images.githubusercontent.com/32777366/32693729-f7b69ae0-c72f-11e7-91ab-1ebbf1386b5d.png)



Also tried to pull a new xposed log and made sure verbose logging is turned on, even though I don't know if this made any difference, but here you go (if you need anything else from me please describe how I can accomplish that and I'm happy to help):

11-11 22:16:59.929 I/Xposed  (  976): -----------------
11-11 22:16:59.929 I/Xposed  (  976): Starting Xposed version 88.2, compiled for SDK 24
11-11 22:16:59.929 I/Xposed  (  976): Device: HTC 10 (HTC), Android version 7.0 (SDK 24)
11-11 22:16:59.929 I/Xposed  (  976): ROM: NRD90M release-keys
11-11 22:16:59.929 I/Xposed  (  976): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:7.0/NRD90M/857212.41:user/release-keys
11-11 22:16:59.929 I/Xposed  (  976): Platform: arm64-v8a, 64-bit binary, system server: yes
11-11 22:16:59.929 I/Xposed  (  976): SELinux enabled: yes, enforcing: yes
11-11 22:16:59.986 I/Xposed  (  976): -----------------
11-11 22:16:59.986 I/Xposed  (  976): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-11 22:17:01.328 I/Xposed  (  976): Detected ART runtime
11-11 22:17:01.343 I/Xposed  (  976): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-11 22:17:02.550 I/Xposed  (  976): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
11-11 22:17:02.572 I/Xposed  (  976):   Loading class ma.wanam.youtubeadaway.Xposed
11-11 22:17:02.573 I/Xposed  (  976):   Loading class ma.wanam.youtubeadaway.ResXposed
11-11 22:17:09.925 I/Xposed  (  990): -----------------
11-11 22:17:09.925 I/Xposed  (  990): Starting Xposed version 88.2, compiled for SDK 24
11-11 22:17:09.925 I/Xposed  (  990): Device: HTC 10 (HTC), Android version 7.0 (SDK 24)
11-11 22:17:09.925 I/Xposed  (  990): ROM: NRD90M release-keys
11-11 22:17:09.925 I/Xposed  (  990): Build fingerprint: htc/pmeuhl_00401/htc_pmeuhl:7.0/NRD90M/857212.41:user/release-keys
11-11 22:17:09.926 I/Xposed  (  990): Platform: arm64-v8a, 32-bit binary, system server: no
11-11 22:17:09.926 I/Xposed  (  990): SELinux enabled: yes, enforcing: yes
11-11 22:17:09.935 I/Xposed  (  990): -----------------
11-11 22:17:09.936 I/Xposed  (  990): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-11 22:17:10.478 I/Xposed  (  990): Detected ART runtime
11-11 22:17:10.492 I/Xposed  (  990): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-11 22:17:11.571 I/Xposed  (  990): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
11-11 22:17:11.583 I/Xposed  (  990):   Loading class ma.wanam.youtubeadaway.Xposed
11-11 22:17:11.584 I/Xposed  (  990):   Loading class ma.wanam.youtubeadaway.ResXposed
11-11 22:18:04.805 I/Xposed  ( 4945): YouTube: com.google.android.youtube 12.43.52 loaded!

**Comment by sutobe** [comment]
Here's the screen record of that SW BF2 clip.
The video needs a fair while to begin playing at the start.
I skipped this and forwarded to the first yellow scheduled ad marker, which will turn the screen black and stop the probably occuring ad.
when this happens I have to go back and then ap again on the minimized video window to persuade youtube to keep on playing the video.
This is the only video so far where I experienced this!

https://youtu.be/G2qIX11m9Yg

**Comment by sutobe** [comment]
Same ol' with the latest module v3.8.0 and latest youtube (which I had to manually install from apkmirror because it wouldnt update for me via Playstore) 12.49.55

cleared cache and app settings, did serveral restarts.

**Comment by ngosang** [comment]
I compiled YoutubeAdAway 3.8.0 form source. Please test the APK and share your results.
Download => https://github.com/wanam/YouTubeAdAway/issues/41#issuecomment-355850303

**Comment by wanam** [comment]
@ngosang why would you do that? The 3.8.0 update is already on the xposed repo.

**Comment by ngosang** [comment]
Sorry, I didn't see. I edited my comment with your build.
