### ISSUE TITLE
Big errorlog in 3.7.0

### ISSUE THREAD

**Issue by StaticsDown** [wanam/YouTubeAdAway#33]
11-10 01:32:02.755 I/Xposed  (  700): -----------------
11-10 01:32:02.755 I/Xposed  (  700): Starting Xposed version 87, compiled for SDK 23
11-10 01:32:02.755 I/Xposed  (  700): Device: LEX720 (LeMobile), Android version 6.0.1 (SDK 23)
11-10 01:32:02.755 I/Xposed  (  700): ROM: Impact Audio V3
11-10 01:32:02.755 I/Xposed  (  700): Build fingerprint: LeEco/ZL1_CN/le_zl1:6.0.1/WAXCNFN5902606012S/letv06011650:user/release-keys
11-10 01:32:02.755 I/Xposed  (  700): Platform: arm64-v8a, 64-bit binary, system server: yes
11-10 01:32:02.755 I/Xposed  (  700): SELinux enabled: yes, enforcing: yes
11-10 01:32:03.783 I/Xposed  (  700): -----------------
11-10 01:32:03.784 I/Xposed  (  700): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-10 01:32:03.986 I/Xposed  (  700): Detected ART runtime
11-10 01:32:03.996 I/Xposed  (  700): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-10 01:32:04.203 I/Xposed  (  700): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
11-10 01:32:04.236 I/Xposed  (  700):   Loading class tw.fatminmin.xposed.minminguard.Main
11-10 01:32:04.358 I/Xposed  (  700): Loading modules from /data/app/de.fivef.audiostreammusicdefault-1/base.apk
11-10 01:32:04.367 I/Xposed  (  700):   Loading class de.fivef.audiostreammusicdefault.DefaultStream
11-10 01:32:04.367 I/Xposed  (  700): Loading modules from /data/app/net.typeblog.webview-1/base.apk
11-10 01:32:04.379 I/Xposed  (  700):   Loading class net.typeblog.webview.ModWebView
11-10 01:32:04.381 I/Xposed  (  700): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
11-10 01:32:04.400 I/Xposed  (  700):   Loading class ma.wanam.youtubeadaway.Xposed
11-10 01:32:04.401 I/Xposed  (  700):   Loading class ma.wanam.youtubeadaway.ResXposed
11-10 01:32:04.402 I/Xposed  (  700): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
11-10 01:32:04.410 I/Xposed  (  700):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
11-10 01:32:04.411 I/Xposed  (  700): Loading modules from /data/app/com.ugglynoodle.allnotificationsexpanded-1/base.apk
11-10 01:32:04.423 I/Xposed  (  700):   Loading class com.ugglynoodle.allnotificationsexpanded.AllNotificationsExpanded
11-10 01:32:04.424 I/Xposed  (  700): Loading modules from /data/app/de.defim.apk.customshare-1/base.apk
11-10 01:32:04.442 I/Xposed  (  700):   Loading class de.defim.apk.customshare.Xposed
11-10 01:32:04.461 I/Xposed  (  700):     [CustomShare] initialized
11-10 01:32:13.015 I/Xposed  (  701): -----------------
11-10 01:32:13.015 I/Xposed  (  701): Starting Xposed version 87, compiled for SDK 23
11-10 01:32:13.015 I/Xposed  (  701): Device: LEX720 (LeMobile), Android version 6.0.1 (SDK 23)
11-10 01:32:13.015 I/Xposed  (  701): ROM: Impact Audio V3
11-10 01:32:13.015 I/Xposed  (  701): Build fingerprint: LeEco/ZL1_CN/le_zl1:6.0.1/WAXCNFN5902606012S/letv06011650:user/release-keys
11-10 01:32:13.015 I/Xposed  (  701): Platform: arm64-v8a, 32-bit binary, system server: no
11-10 01:32:13.015 I/Xposed  (  701): SELinux enabled: yes, enforcing: yes
11-10 01:32:13.017 I/Xposed  (  701): -----------------
11-10 01:32:13.017 I/Xposed  (  701): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-10 01:32:13.165 I/Xposed  (  701): Detected ART runtime
11-10 01:32:13.174 I/Xposed  (  701): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-10 01:32:13.321 I/Xposed  (  701): Loading modules from /data/app/tw.fatminmin.xposed.minminguard-1/base.apk
11-10 01:32:13.334 I/Xposed  (  701):   Loading class tw.fatminmin.xposed.minminguard.Main
11-10 01:32:13.392 I/Xposed  (  701): Loading modules from /data/app/de.fivef.audiostreammusicdefault-1/base.apk
11-10 01:32:13.397 I/Xposed  (  701):   Loading class de.fivef.audiostreammusicdefault.DefaultStream
11-10 01:32:13.398 I/Xposed  (  701): Loading modules from /data/app/net.typeblog.webview-1/base.apk
11-10 01:32:13.403 I/Xposed  (  701):   Loading class net.typeblog.webview.ModWebView
11-10 01:32:13.404 I/Xposed  (  701): Loading modules from /data/app/ma.wanam.youtubeadaway-1/base.apk
11-10 01:32:13.410 I/Xposed  (  701):   Loading class ma.wanam.youtubeadaway.Xposed
11-10 01:32:13.410 I/Xposed  (  701):   Loading class ma.wanam.youtubeadaway.ResXposed
11-10 01:32:13.410 I/Xposed  (  701): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
11-10 01:32:13.417 I/Xposed  (  701):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
11-10 01:32:13.418 I/Xposed  (  701): Loading modules from /data/app/com.ugglynoodle.allnotificationsexpanded-1/base.apk
11-10 01:32:13.423 I/Xposed  (  701):   Loading class com.ugglynoodle.allnotificationsexpanded.AllNotificationsExpanded
11-10 01:32:13.424 I/Xposed  (  701): Loading modules from /data/app/de.defim.apk.customshare-1/base.apk
11-10 01:32:13.436 I/Xposed  (  701):   Loading class de.defim.apk.customshare.Xposed
11-10 01:32:13.448 I/Xposed  (  701):     [CustomShare] initialized
11-10 01:32:20.725 I/Xposed  ( 1633): getWebViewPackageName
11-10 01:33:13.546 I/Xposed  ( 4131): YouTube: com.google.android.youtube 12.43.52 loaded!
11-10 01:33:13.799 I/Xposed  ( 4131): YouTube AdAway: Successfully hooked ads DB yka
11-10 01:33:14.759 I/Xposed  ( 4131): YouTube AdAway: Successfully hooked ads wrapper 
11-10 01:33:14.810 E/Xposed  ( 4131): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
11-10 01:33:14.810 E/Xposed  ( 4131): 	at tw.fatminmin.xposed.minminguard.blocker.NameBlocking$1.beforeHookedMethod(NameBlocking.java:108)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.ViewGroup.addView(<Xposed>)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ma.wanam.youtubeadaway.XYouTubeLayouts$1.handleLayoutInflated(XYouTubeLayouts.java:64)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.callbacks.XC_LayoutInflated.call(XC_LayoutInflated.java:57)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.content.res.XResources$2.afterHookedMethod(XResources.java:219)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(<Xposed>)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(<Xposed>)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(<Xposed>)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at tcr.<init>(SourceFile:4)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at epw.get(SourceFile:7)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at akdb.get(SourceFile:10)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at foe.get(SourceFile:112)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at akdb.get(SourceFile:10)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at eoo.a(SourceFile:42)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at kw.b(SourceFile:275)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.a(SourceFile:476)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.c(SourceFile:705)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.a(SourceFile:784)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at kn.f(SourceFile:235)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.b(SourceFile:1180)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.a(SourceFile:1082)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.b(SourceFile:1057)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.j(SourceFile:1001)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.c(SourceFile:1567)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ll.m(SourceFile:1544)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ld.onStart(SourceFile:235)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at aeb.onStart(SourceFile:38)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at cmr.onStart(SourceFile:12)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at ckg.onStart(SourceFile:11)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at com.google.android.apps.youtube.app.WatchWhileActivity.onStart(SourceFile:339)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.Activity.performStart(Activity.java:6341)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2457)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2556)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.ActivityThread.access$1200(ActivityThread.java:155)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.os.Looper.loop(Looper.java:148)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at android.app.ActivityThread.main(ActivityThread.java:5645)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at java.lang.reflect.Method.invoke(Native Method)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-10 01:33:14.810 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
11-10 01:33:14.811 E/Xposed  ( 4131): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
11-10 01:33:14.811 E/Xposed  ( 4131): 	at tw.fatminmin.xposed.minminguard.blocker.NameBlocking$1.beforeHookedMethod(NameBlocking.java:108)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.view.ViewGroup.addView(<Xposed>)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at ma.wanam.youtubeadaway.XYouTubeLayouts$1.handleLayoutInflated(XYouTubeLayouts.java:64)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.callbacks.XC_LayoutInflated.call(XC_LayoutInflated.java:57)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.content.res.XResources$2.afterHookedMethod(XResources.java:219)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(<Xposed>)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(<Xposed>)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-10 01:33:14.811 E/Xposed  ( 4131): 	at de.robv.android.xposed.XposedBridge.handleHookedMe

**Comment by wanam** [comment]
```
11-10 01:33:14.810 E/Xposed ( 4131): at tw.fatminmin.xposed.minminguard.blocker.NameBlocking$1.beforeHookedMethod(NameBlocking.java:108)
11-10 01:33:14.810 E/Xposed ( 4131): at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
11-10 01:33:14.810 E/Xposed ( 4131): at android.view.ViewGroup.addView()
11-10 01:33:14.810 E/Xposed ( 4131): at ma.wanam.youtubeadaway.XYouTubeLayouts$1.handleLayoutInflated(XYouTubeLayouts.java:64)
```
It seems minminguard module is interfering with my module [here](https://github.com/chiehmin/MinMinGuard/blob/master/app/src/main/java/tw/fatminmin/xposed/minminguard/blocker/NameBlocking.java#L108).

```
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                View view = (View) param.args[0];
                if (isAdView(view.getContext(), pkgName, view)) {
                    Main.removeAdView(view, pkgName, true);
                }
            }
```
He tries to verify if the added view is an ad, but somehow the view at that point is null, i think the dev should check that before getting the context.
