### ISSUE TITLE
latest update Memory leak!?

### ISSUE THREAD

**Issue by Matt8119** [wanam/YouTubeAdAway#34]
after updating to the latest update, my phone Nexus 6p 7.1.1 freezes and crashes to the point its not even usable.  once i downgraded to the second to last update, my phone is once again usable.

**Comment by wanam** [comment]
Please post your logcat.

**Comment by ngosang** [comment]
I compiled YoutubeAdAway 3.8.0 form source. Please test the APK and share your results.
Download => https://github.com/wanam/YouTubeAdAway/issues/41#issuecomment-355850303

**Comment by wanam** [comment]
Closed for no feedback.
Please re-open it with the logs if you still get any issues with 4.1.0.
