### ISSUE TITLE
Ads on the newest youtube update

### ISSUE THREAD

**Issue by mathieu3500** [wanam/YouTubeAdAway#35]
Here is the screen of the ad
![screenshot_20171114-000848](https://user-images.githubusercontent.com/33648159/32763907-93cb3480-c8d0-11e7-8cbe-67a5b7d89cd2.png)
 And here the log
![screenshot_20171114-000912](https://user-images.githubusercontent.com/33648159/32763919-a9efb8e4-c8d0-11e7-9aa0-d3b05b8e9358.png)

Youtube AdAway ver. 3.7.0

Thanks wanam for your amazing work ! :) and thank in advance for your help.

**Comment by wizlifa** [comment]
Getting ads on nexus 6, android 7.1.1, build NGI77B
[xposed_error_20171115_231035.log]

**Comment by theArhar** [comment]
advertisment appears on video start

[xposed_error_20171116_210905.log](https://github.com/wanam/YouTubeAdAway/files/1479672/xposed_error_20171116_210905.log)
deleted youtube completely - no differense

**Comment by Quanalogy** [comment]
Same here;

11-17 08:30:33.384 I/Xposed  ( 4531): Starting Xposed version 88.2, compiled for SDK 25
11-17 08:30:33.384 I/Xposed  ( 4531): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.2 (SDK 25)
11-17 08:30:33.384 I/Xposed  ( 4531): ROM: NZH54D
11-17 08:30:33.384 I/Xposed  ( 4531): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/07311003:user/release-keys
11-17 08:30:33.384 I/Xposed  ( 4531): Platform: arm64-v8a, 64-bit binary, system server: yes
11-17 08:30:33.384 I/Xposed  ( 4531): SELinux enabled: yes, enforcing: no
11-17 08:30:36.401 I/Xposed  ( 4531): -----------------
11-17 08:30:36.402 I/Xposed  ( 4531): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-17 08:30:36.485 I/Xposed  ( 4531): Detected ART runtime
11-17 08:30:36.491 I/Xposed  ( 4531): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-17 08:30:36.574 I/Xposed  ( 4531): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-2/base.apk
11-17 08:30:36.590 I/Xposed  ( 4531):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
11-17 08:30:36.592 I/Xposed  ( 4531): Loading modules from /data/app/de.defim.apk.bootmanager-1/base.apk
11-17 08:30:36.608 I/Xposed  ( 4531):   Loading class de.defim.apk.bootmanager.Xposed
11-17 08:30:36.620 I/Xposed  ( 4531):     [BootManager] initialized
11-17 08:30:36.621 I/Xposed  ( 4531): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
11-17 08:30:36.629 I/Xposed  ( 4531):   Loading class ma.wanam.youtubeadaway.Xposed
11-17 08:30:36.630 I/Xposed  ( 4531):   Loading class ma.wanam.youtubeadaway.ResXposed
11-17 08:31:15.397 I/Xposed  ( 7763): YouTube: com.google.android.youtube 12.44.53 loaded!
11-17 08:31:16.329 I/Xposed  ( 7763): YouTube AdAway: Successfully hooked ads DB ypj
11-17 08:31:17.382 I/Xposed  ( 7763): YouTube AdAway: Successfully hooked ads wrapper 
11-17 08:31:20.974 I/Xposed  ( 7763): YouTube AdAway: Successfully hooked ads fetchers
11-17 16:23:43.977 I/Xposed  (29006): YouTube: com.google.android.youtube 12.44.53 loaded!
11-17 16:23:48.184 F/art     (29006): art/runtime/class_linker.cc:2728] Check failed: found_virtual Didn't find oat method index for virtual method: void android.icu.impl.Assert.<init>()
11-17 16:42:47.005 I/Xposed  (30887): YouTube: com.google.android.youtube 12.44.53 loaded!
11-17 16:42:47.364 I/Xposed  (30887): YouTube AdAway: Successfully hooked ads DB ypj
11-17 16:42:48.033 I/Xposed  (30887): YouTube AdAway: Successfully hooked ads wrapper 
11-17 16:42:49.672 I/Xposed  (30887): YouTube AdAway: Successfully hooked ads fetchers

**Comment by evo744** [comment]
Yeah, ads here too on youtube 12.43.52 and 12.44.53. Only video ads

**Comment by blackman91** [comment]
Yep me too on latest youtube with latest youtube adaway please fix it!

**Comment by panyuhang93** [comment]
Thank you very much!

**Comment by OverWorldD** [comment]
Ads here as well. YT 12.44.53, Nougat .7.1.2 module 3.6.1 using xposed systemless, Magisk.

Hooks look good though. Seems only unskippable ads are affected. Getting full "headspace" ads for example.

11-20 01:40:05.259 I/Xposed  (  436): -----------------
11-20 01:40:05.259 I/Xposed  (  436): Starting Xposed version 88.1 (Systemless by topjohnwu), compiled for SDK 25
11-20 01:40:05.259 I/Xposed  (  436): Device: Moto G4 Plus (Motorola), Android version 7.1.2 (SDK 25)
11-20 01:40:05.259 I/Xposed  (  436): ROM: NJH47F
11-20 01:40:05.259 I/Xposed  (  436): Build fingerprint: motorola/athene_f/athene_f:7.0/NPJ25.93-14/16:user/release-keys
11-20 01:40:05.259 I/Xposed  (  436): Platform: armeabi-v7a, 32-bit binary, system server: yes
11-20 01:40:05.259 I/Xposed  (  436): SELinux enabled: yes, enforcing: yes
11-20 01:40:06.281 I/Xposed  (  436): -----------------
11-20 01:40:06.281 I/Xposed  (  436): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-20 01:40:06.996 I/Xposed  (  436): Detected ART runtime
11-20 01:40:07.008 I/Xposed  (  436): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
11-20 01:40:07.829 I/Xposed  (  436): Loading modules from /data/app/com.pyler.youtubebackgroundplayback-1/base.apk
11-20 01:40:07.852 I/Xposed  (  436):   Loading class com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback
11-20 01:40:07.858 I/Xposed  (  436): Loading modules from /data/app/com.aviraxp.adblocker.continued-1/base.apk
11-20 01:40:07.877 I/Xposed  (  436):   Loading class com.aviraxp.adblocker.continued.hook.HookLoader
11-20 01:40:08.096 I/Xposed  (  436): Loading modules from /data/app/ma.wanam.youtubeadaway-2/base.apk
11-20 01:40:08.119 I/Xposed  (  436):   Loading class ma.wanam.youtubeadaway.Xposed
11-20 01:40:08.119 I/Xposed  (  436):   Loading class ma.wanam.youtubeadaway.ResXposed
11-20 01:41:24.817 I/XposedInstaller( 6896): XposedInstaller - 1508330700000 - 3.1.2 by dvdandroid - 18/10/17
11-20 01:41:25.451 I/XposedInstaller( 6896): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/13288.xml.gz with status 0 (error: null), size 23933 bytes
11-20 01:41:26.101 I/XposedInstaller( 6896): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 13318 (14 new / 0 removed modules)
11-20 01:41:37.436 I/Xposed  ( 7311): YouTube: com.google.android.youtube 12.44.53 loaded!
11-20 01:41:40.056 I/Xposed  ( 7311): YouTube AdAway: Successfully hooked ads DB ypj
11-20 01:41:42.440 I/Xposed  ( 7311): YouTube AdAway: Successfully hooked ads wrapper 
11-20 01:41:48.597 I/Xposed  ( 7311): YouTube AdAway: Successfully hooked ads fetchers
11-20 01:42:14.292 I/XposedInstaller( 8734): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/13318.xml.gz with status 0 (error: null), size 66 bytes
11-20 01:42:14.315 I/XposedInstaller( 8734): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 13318 (0 new / 0 removed modules)
11-20 01:45:54.894 I/Xposed  (10349): YouTube: com.google.android.youtube 12.44.53 loaded!
11-20 01:45:55.847 I/Xposed  (10349): YouTube AdAway: Successfully hooked ads DB ypj
11-20 01:45:58.107 I/Xposed  (10349): YouTube AdAway: Successfully hooked ads wrapper 
11-20 01:46:03.456 I/Xposed  (10349): YouTube AdAway: Successfully hooked ads fetchers
11-20 01:48:28.651 I/XposedInstaller( 8734): RepoLoader -> Downloaded http://dl.xposed.info/repo/partial/13318.xml.gz with status 0 (error: null), size 66 bytes
11-20 01:48:28.674 I/XposedInstaller( 8734): RepoLoader -> Updated repository http://dl.xposed.info/repo/full.xml.gz to version 13318 (0 new / 0 removed modules)

**Comment by blackman91** [comment]
Is this ever gonna get fixed? the amount of ads that appear is getting ridiculous.

**Comment by r2987554** [comment]
I think something was changed in YT that wasn't part of its app (like an issue from earlier this year when 1080 and higher resolution suddenly became unavailable on various devices and versions of both Android and YT app).

**Comment by Lightfire228** [comment]
@r2987554, I'd have to agree with you. I downloaded an older apk that I knew was ad free as of the latest YT adaway, and the video ads were back. So it must have been a server side change. 

Also, same symptoms, only video ads at the star of the video (never ads during a video) and banner ads below the video player when not full screened

**Comment by iDamnation** [comment]
Updates went inactive or couldnt crack the code to block the ads yet? More and more ads are appearing now. Even happened once in the middle of a video.

**Comment by adelino660** [comment]
Hi i got it working with an older version of youtube adaway 3.5.1 and using youtube version 12.05.53

This should fix the problem, just don't update youtube nor use a newer version of youtube adaway.

I never updated the app for my tablet with this setup, and i was having the same issues once i updated to the latest youtube version along with the youtube adaway module. ( on my phone) I reverted back to the older versions on my phone and the adblocking is back in business.

**Comment by OverWorldD** [comment]
Awesome, thanx. I think it works for me too!

**Comment by blackman91** [comment]
This alternative works better:
https://forum.xda-developers.com/android/apps-games/app-iytbp-injected-youtube-background-t3560900

This seems dead now.

**Comment by Grossdm** [comment]
Thanks to @blackman91 - that looks very promising. I'll give that a try tomorrow.

👍

**Comment by ngosang** [comment]
I compiled YoutubeAdAway 3.8.0 form source. Please test the APK and share your results.
Download => https://github.com/wanam/YouTubeAdAway/issues/41#issuecomment-355850303

**Comment by wanam** [comment]
Fixed on 4.1.0 update.
