### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by AhmedNazir** [wanam/YouTubeAdAway#38]
Youtube is still showing ads.

I Have a Request :
When you update youtube AdAway, please provide  compatible version of youtube app with download link.
That's helps us.
we just download AdAway and compatible youtube app and enjoy it....
finding older version app is like finding things in a garbage...

Thanks for making such a Module for poor peoples..

**Comment by panyuhang93** [comment]
http://repo.xposed.info/module/ma.wanam.youtubeadaway
3.7.0  Tested against YouTube 12.43.52

**Comment by r2987554** [comment]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-12-43-52-release/

**Comment by AhmedNazir** [comment]
Thanks....
