### ISSUE TITLE
does not work with version YouTube v12.45.56

### ISSUE THREAD

**Issue by geronimoronin** [wanam/YouTubeAdAway#39]
does not work with version YouTube v12.45.56

**Comment by r2987554** [comment]
Heads up: current version of the module (3.7.0) and earlier releases may be ineffective regardless of YT app version it's used with, including the one it was tested against (12.43.52 in case of 3.7.0), due to apparent server-side changes made by YouTube. Waiting for news from Wanam.

**Comment by adelino660** [comment]
Hi i got it working with an older version of youtube adaway 3.5.1 and using youtube version 12.05.53

This should fix the problem, just don't update youtube nor use a newer version of youtube adaway. 

I never updated the app for my tablet with this setup, and i was having the same issues once i updated to the latest youtube version along with the youtube adaway module. I tried using the older versions and it has been successful. Hope this helps.

**Comment by theArhar** [comment]
looks like Wanam lost this war
today I am getting advertisment even on "old" configuration

**Comment by ibigfire** [comment]
Hey wanam, don't mean to be a bother, but haven't seen any activity from you in a month or so now since it stopped working.  Just a peep to know what the status is of this project would be very much appreciated by many, I think, if possible.  Thank you.

**Comment by wanam** [comment]
Sorry for that, i cannot say it's abandoned but i'm busy with other things (family and work), feel free to contribute, it's the main reason i open sourced the module.

**Comment by Bigdogmacho** [comment]
The last working combination that worked for me was 3.5.3 in conjunction with YouTube 12.12.53

**Comment by theArhar** [comment]
Please explain how you debug this thing, maybe I can look into it, I have android studio and little experience in this

**Comment by wanam** [comment]
@theArhar You need to decompile the YouTube App and try to find any occurrence of the classes that manage ads views/fetchers, and then figure out how you can brute force to lookup and hook them, it would be much more easier to catch those ads if the app was not proguarded, but we have to deal with it this way and try to follow some logs and hardcoded Strings.

**Comment by ngosang** [comment]
I compiled YoutubeAdAway 3.8.0 form source. Please test the APK and share your results.
Download => https://github.com/wanam/YouTubeAdAway/issues/41#issuecomment-355850303

**Comment by wanam** [comment]
v12.45.56 and newer versions should be supported now on 4.1.0.
