### ISSUE TITLE
Ads with v4.0 and YouTube 13.01.52

### ISSUE THREAD

**Issue by sutobe** [wanam/YouTubeAdAway#43]
Hey,

thanks for the new update, yet I still sometimes get ads. To narrow it down they mostly appear when I watch Star Wars related stuff on channels like Generation Tech or Star Wars Theory! 
Most of the time those are amazon ads for various products, often audio books, with this new Adaway version it appears to be a little less but then I get SW mobile game clips before the actual video. 

I extracted 2 changelogs as explained in the 4.0 changelog and made  Screenshots, cleared Youtube cache before starting the app.
Phone is a HTC 10 on Nougat if this is important. 

Github says the file is to long so I uploaded both to a Google drive folder!:
https://drive.google.com/open?id=1TFpkCiZo05TTzcwUYeTgQdsZqjCTWHbH

**Comment by sutobe** [comment]
![screenshot_20180117-173823](https://user-images.githubusercontent.com/32777366/35055373-5b65003c-fbaf-11e7-8cc5-66cc4d0d9cf3.png)
![Uploading Screenshot_20180106-101352.png…]()
![Uploading Screenshot_20180117-173611.png…]()
![Uploading Screenshot_20180117-173602.png…]()

**Comment by wanam** [comment]
@sutobe thanks for report.
Unfortunately i wasted more than 5GB of my mobile data trying to refine the criteria of the ad views that i should hide, so if you or anyone else can build the Apk from sources, i can push 4.0.0 sources and tel you how to debug.

**Comment by sutobe** [comment]
Unfortunately I have no idea how this works.

Could do with a step by step explanation maybe......

**Comment by wanam** [comment]
Can you try the new update 4.0.1, I'm forcing the "skip ad" button to stay visible with no count down, hope that helps with non skipable videos as well.

**Comment by sutobe** [comment]
Good morning, already installed it, got only one ad so far, no surprise, it was an Amazon ad before a video on a star wars channel (Star Wars Explained).
Only one so far. And also just once so far. 

I am at work right now, I could try and provoke an ad later, what logs do you need?

**Comment by sutobe** [comment]
Have to mention YouTube also got an update on 13.01.53

**Comment by wanam** [comment]
Nice! wasted hours yesterday trying to reproduce any ad with no success.
I have 3 question about that ad:
1- Was the skippable?
2- Did you get any count down timer on that ad?
3- Did you click on skip button or let it ends itself?

I was trying to implement a way to perform an auto click on the skip ad button, but didn't manage to get any ad to test my implementation.

I simplified my hooks, devs who aim to help does not need to bother about proguarded sources anymore, will push my sources soon.

**Comment by sutobe** [comment]
Crap already got some new ads (very few and way less occuring than before though!!) and forgot you posted the checklist -.-

trying to reproduce some now.

most of the time it looks like the 2 screenshots I posted here.  all of them are videos that play before the clip I want to watch.

When it's an Amazon ad I get the Amazon banner below the player window as can be seen in the screenshot.

the other ads mostly consist of mobile game or movie trailers without a banner.

All of them come with a link "zum werbetreibenden springen", German for bad translated "jump to ad creator". 

Trying to answer your 3 questions now. Log file of xposed says nothing, only that module 4.0.1 loaded with youtube 13.01.53

**Comment by sutobe** [comment]
So already got a Star wars mobile game ad on Generation Tech channel.

1.it was skippable after 2 clicks 

2.didn't see any timer counting down

3. I clicked on the skip button twice and it did end, but maybe there was a non visible timer, dont know.

**Comment by sutobe** [comment]
just got two ads (one of them was a Dominos Pizza) and couldnt skip them with the skip button, but I noticed there is in fact a timer that shows how long the app is going.
You can see it on the screenshots I posted earlier, it's that little yellow bar filling up below the ad.

**Comment by wanam** [comment]
In-videos ads have been fixed on 4.1.0.
