### ISSUE TITLE
youtube adaway error on YT 13.01.53

### ISSUE THREAD

**Issue by woo9901** [wanam/YouTubeAdAway#47]
[xposed_error_20180118_210357.log](https://github.com/wanam/YouTubeAdAway/files/1642742/xposed_error_20180118_210357.log)

I think adaway doesn't work when I use youtube in landscape mode.

used version
- YT Adaway: 4.0.0
- YT: 13.01.53

**Comment by woo9901** [comment]
+ When I use youtube in portrait mode, adaway works well.....

**Comment by xerta555** [comment]
Hello @woo9901 
Do you have edit your HOST file by an app like [AdAway](https://adaway.org/) or have you apply any other MOD(s) ?

Thanks in advance.

**Comment by xerta555** [comment]
@woo9901 Ok, thanks for theses infos..
I expect that wanam will find another way to block all ads.

**Comment by wanam** [comment]
Some crashes introduced on 4.0.0 were fixed on 4.1.0, if you are on Oreo and still getting any YouTube crashes, follow [this issue](https://github.com/rovo89/Xposed/issues/325) for further fix.
