### ISSUE TITLE
youtubeadaway ads log

### ISSUE THREAD

**Issue by Giowi** [wanam/YouTubeAdAway#49]
Here my log.
It's always amazon ads
[xposed_error_20180119_000401.log](https://github.com/wanam/YouTubeAdAway/files/1644760/xposed_error_20180119_000401.log)

**Comment by Giowi** [comment]
Amazon ads on youtubeadaway 4.0.1
[xposed_error_20180119_154846.log](https://github.com/wanam/YouTubeAdAway/files/1646889/xposed_error_20180119_154846.log)

**Comment by wanam** [comment]
Something is wrong with your log encoding, i can't read them.
Can you get a logcat while reproducing the ad?
Are those ads skippable? do you get the count down timer for those ads?

**Comment by Giowi** [comment]
Strange You cannot read my log
I get the logcat while reproducing the ad. It's always amazon
I get the count down timer

**Comment by wanam** [comment]
Fixed on 4.1.0
