### ISSUE TITLE
Ads on 4.0

### ISSUE THREAD

**Issue by dvdhngs** [wanam/YouTubeAdAway#50]
[xposed_error_20180118_124140.log](https://github.com/wanam/YouTubeAdAway/files/1646472/xposed_error_20180118_124140.log)
[xposed_error_20180118_124712.log](https://github.com/wanam/YouTubeAdAway/files/1646474/xposed_error_20180118_124712.log)

**Comment by wanam** [comment]
A few more words please, a screenshot at least would help next time.
4.1.0 should hide in-video ads.
