### ISSUE TITLE
Still some ads with 4.0.1

### ISSUE THREAD

**Issue by cbr3k** [wanam/YouTubeAdAway#54]
Opened the video in another app (redditsync) and clicked through to the YouTube app.

01-21 10:30:42.674 I/Xposed  ( 5835): YouTube: com.google.android.youtube 13.01.53 loaded with module version 4.0.1
01-21 10:30:42.880 I/Xposed  ( 4697): skip_ad_button: set to visible
01-21 10:30:42.880 I/Xposed  ( 4697): performRecursiveClick 0
01-21 10:30:43.079 I/Xposed  ( 4697): detected visible ad: ad_title_layout
01-21 10:30:48.968 I/Xposed  ( 5937): YouTube: com.google.android.youtube 13.01.53 loaded with module version 4.0.1
01-21 10:30:50.110 I/Xposed  ( 5937): detected visible ad: info_card_teaser_wrapper
01-21 10:30:50.119 I/Xposed  ( 5937): detected visible ad: promo_expand_arrow
01-21 10:30:50.119 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:30:50.120 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:30:50.264 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:30:50.264 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:30:50.418 I/Xposed  ( 5937): detected visible ad: promo_expand_arrow
01-21 10:30:50.418 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:30:50.418 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:30:50.430 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:30:50.430 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:30:51.528 I/Xposed  ( 5937): performRecursiveClick 0
01-21 10:30:51.530 I/Xposed  ( 5937): SkipAdButton.a()
01-21 10:30:51.538 I/Xposed  ( 5937): detected inflated ad: ad_countdown
01-21 10:30:51.547 I/Xposed  ( 5937): skip_ad_button: set to visible
01-21 10:30:51.547 I/Xposed  ( 5937): performRecursiveClick 0
01-21 10:30:51.548 I/Xposed  ( 5937): detected visible ad: ad_count_text
01-21 10:30:51.549 I/Xposed  ( 5937): detected visible ad: ad_timer_text
01-21 10:30:51.550 I/Xposed  ( 5937): skip_ad_button: set to visible
01-21 10:30:51.550 I/Xposed  ( 5937): performRecursiveClick 0
01-21 10:30:51.550 I/Xposed  ( 5937): detected visible ad: ad_countdown
01-21 10:30:51.550 I/Xposed  ( 5937): detected visible ad: ad_countdown
01-21 10:30:51.599 I/Xposed  ( 5937): detected inflated ad: main_companion_container
01-21 10:30:51.628 I/Xposed  ( 5937): detected visible ad: ad_cta_button_text
01-21 10:30:51.629 I/Xposed  ( 5937): detected visible ad: app_promotion_companion_card
01-21 10:30:52.867 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:30:52.867 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:30:56.571 I/Xposed  ( 5937): skip_ad_button: set to visible
01-21 10:30:56.572 I/Xposed  ( 5937): performRecursiveClick 0
01-21 10:31:01.341 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:31:01.341 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:31:01.346 I/Xposed  ( 5937): detected visible ad: promo_expand_arrow
01-21 10:31:01.346 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:31:01.346 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:31:01.635 I/Xposed  ( 5937): skip_ad_button: set to visible
01-21 10:31:01.635 I/Xposed  ( 5937): performRecursiveClick 0
01-21 10:31:03.123 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:31:03.124 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed
01-21 10:31:03.456 I/Xposed  ( 5937): detected visible ad: promo_website_thumbnail_expanded
01-21 10:31:03.456 I/Xposed  ( 5937): detected visible ad: promo_thumbnail_collapsed

**Comment by cbr3k** [comment]
Holy moley! Sorry, that wasn't supposed to happen.

**Comment by wanam** [comment]
Fixed on 4.1.0
