### ISSUE TITLE
Crashing when video start

### ISSUE THREAD

**Issue by EDDiCTS** [wanam/YouTubeAdAway#55]
Conflict with the ads,Please check that out

**Comment by blistex** [comment]
YES! unfortunately I have to second this... yt app crashes while browsing or after selecting a video. Only way do stop crashing it is to disable YouTubeAdAway.

Maaaaaaan. Honestly one of the greatest modules that had stopped working, and after seeing a update I was super happy. But this version doesn't block ads + crashes the app. Not complaining just telling how sad I am.

If it's any use I would upload the log and so on but i see many people already posted their logs with similar issues.

**Comment by wanam** [comment]
Post your logs please.

**Comment by blistex** [comment]
[xposed_error_20180124_014756.log](https://github.com/wanam/YouTubeAdAway/files/1658112/xposed_error_20180124_014756.log)

with the newest 4.0.3

YouTube app crashes 8/10 times instantly! Doesn't matter if autoplay is on or off! Ad's still appear if I can get to select a video. (mainly amazon germany ad's).

**Comment by wanam** [comment]
@blistex Please use only one thread per issue.
@EDDiCTS This should be fixed on 4.1.0, if the your issue persists, create an issue with more details and logs.
