### ISSUE TITLE
Still ads with experimental 4.0.3

### ISSUE THREAD

**Issue by telxonius** [wanam/YouTubeAdAway#57]
I'm still getting ads on the 4.0.3 debug version. I am only even doing this because I believe there might be some hope left. I have switched to newpipe for actually watching vids, and only use the official version for trying to help you guys fix this. 
![screenshot_2018-01-27-10-20-27](https://user-images.githubusercontent.com/33646843/35473994-b5b927fc-034d-11e8-8e16-0ff6c965faba.png)

It refuses to let me upload a log, bluetooth crashes, and when I try to save it, it's not in the location specified. Tried sending it to my gmail and that failed too. Done playing with this.

**Comment by wanam** [comment]
Fixed on 4.1.0

**Comment by telxonius** [comment]
working with 4.1.0 MUCH better, thanks!
