### ISSUE TITLE
4.2.0 Chromecast issues

### ISSUE THREAD

**Issue by cbr3k** [wanam/YouTubeAdAway#61]
When connected to a Chromecast, the queue drawer always shows "Skip ad" at the right end, which means it's not possible to use the pause control which is visible under it, and while a video is playing there's a repetitive click noise.

**Comment by wanam** [comment]
It should be easy to fix, you can still use the video controls to pause and resume.
I didn't manage to reproduce the click noise, but it should also go away with the fix on my head.
![screenshot_20180213-220410](https://user-images.githubusercontent.com/739291/36176460-90977dd2-110a-11e8-9999-d242ae7c8c7c.png)

**Comment by wanam** [comment]
Can you try [this test version](https://www.dropbox.com/sh/mh4xl6nx2m1uysr/AAAhtPopCdwpiDZEyjPYLTXRa?dl=0) and report back?
You need to uninstall the release version first.

**Comment by cbr3k** [comment]
4.3.0 sort of works, in that the Skip ad text and the clicking sound are gone, however the drawer doesn't display any text - it usually shows the name of the playing video and the position in the queue/number of items queued.

**Comment by wanam** [comment]
Okay thanks for the feedback, i will check that.

**Comment by wanam** [comment]
Can you try the new update?

**Comment by wanam** [comment]
You are welcome, thanks for your support.
