### ISSUE TITLE
since the last update YouTube crashes from 2-3 seconds after the start

### ISSUE THREAD

**Issue by jokerzz81** [wanam/YouTubeAdAway#62]

**Comment by wanam** [comment]
There is no errors on your xposed logs, can you get a logcat of the crash?

**Comment by jokerzz81** [comment]
how do I do that?

**Comment by wanam** [comment]
[This way](http://bfy.tw/Gj2b) :) .

**Comment by jokerzz81** [comment]
thank you brilliant idea :)

I hope that's right.

02-21 17:30:45.854 I/Timeline(3520): Timeline: Activity_windows_visible id: ActivityRecord{a934768 u0 com.teslacoilsw.launcher/.NovaLauncher t657} time:4992817
02-21 17:30:47.015 I/Timeline(5294): Timeline: Activity_launch_request id:com.google.android.youtube time:4993977
02-21 17:30:47.015 I/ActivityManager(3520): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.youtube/.app.honeycomb.Shell$HomeActivity bnds=[540,1213][810,1498] (has extras)} from uid 10220 on display 0
02-21 17:30:47.069 V/BoostFramework(3520): BoostFramework() : mPerf = com.qualcomm.qti.Performance@cde0d61
02-21 17:30:47.069 I/ActivityManager(3520): Start proc 29642:com.google.android.youtube/u0a189 for activity com.google.android.youtube/.app.honeycomb.Shell$HomeActivity
02-21 17:30:47.189 I/Xposed  (29642): YouTube: com.google.android.youtube 13.06.53 loaded with module version 4.3.2
02-21 17:30:47.336 W/YouTube (29642): Fetching the Gservices key 'failsafe_clear_cache_release_13_02' before the end of the bulk initialization
02-21 17:30:47.379 W/YouTube (29642): Fetching the Gservices key 'disable_binder_callback_flush' before the end of the bulk initialization
02-21 17:30:47.719 W/System  (29642): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000b/n/armeabi-v7a
02-21 17:30:47.720 W/System  (29642): ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000b/n/armeabi
02-21 17:30:47.810 D/ConnectivityService(3520): listenForNetwork for Listen from uid/pid:10189/29642 for NetworkRequest [ id=88, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
02-21 17:30:47.813 D/DynamitePackage(29642): Instantiated singleton DynamitePackage.
02-21 17:30:47.813 D/DynamitePackage(29642): Instantiating com.google.android.gms.ads.adshield.ChimeraAdShieldCreatorImpl
02-21 17:30:47.996 I/libcamera(605): HAL_getCameraInfo: E cameraId=0
02-21 17:30:47.996 I/libcamera(605): HAL_getCameraInfo: X
02-21 17:30:48.006 I/libcamera(605): HAL_getCameraInfo: E cameraId=1
02-21 17:30:48.006 I/libcamera(605): HAL_getCameraInfo: X
02-21 17:30:48.254 I/CrashMetricService(29642): Startup metric for 'PRIMES_CRASH_MONITORING_INITIALIZED' dropped.
02-21 17:30:48.360 W/art     (29642): Suspending all threads took: 5.032ms
02-21 17:30:48.450 I/art     (29642): Background partial concurrent mark sweep GC freed 48495(4MB) AllocSpace objects, 30(1136KB) LOS objects, 39% free, 23MB/38MB, paused 8.598ms total 130.202ms
02-21 17:30:48.455 I/CrashMetricService(29642): Startup metric for 'PRIMES_FIRST_ACTIVITY_LAUNCHED' dropped.
02-21 17:30:48.491 I/Timeline(29642): Timeline: Activity_launch_request id:com.google.android.youtube time:4995453
02-21 17:30:48.491 I/ActivityManager(3520): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x4000000 cmp=com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity bnds=[540,1213][810,1498] (has extras)} from uid 10189 on display 0
02-21 17:30:48.632 D/WVCdm   (605): Instantiating CDM.
02-21 17:30:48.835 W/YT.MDX.xlw(29642): CastAppId for type 0 not found. Defaulting to mainCastAppId.
02-21 17:30:48.865 W/YT.MDX.xlw(29642): CastAppId for type 0 not found. Defaulting to mainCastAppId.
02-21 17:30:48.930 E/GoogleConversionReporter(29642): Error sending ping
02-21 17:30:48.930 E/GoogleConversionReporter(29642): ambw: Exception in CronetUrlRequest: net::ERR_CONNECTION_REFUSED, ErrorCode=7, InternalErrorCode=-102, Retryable=false
02-21 17:30:48.930 E/GoogleConversionReporter(29642): 	at org.chromium.net.impl.CronetUrlRequest.onError(SourceFile:208)
02-21 17:30:49.124 D/WifiStateMachine(3520): starting scan for "KAP5G"-WPA_PSK with 5180
02-21 17:30:49.556 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:49.593 W/YT.MDX.xlw(29642): CastAppId for type 0 not found. Defaulting to mainCastAppId.
02-21 17:30:49.793 D/OpenGLRenderer(29642): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-21 17:30:49.805 I/Choreographer(29642): Skipped 45 frames!  The application may be doing too much work on its main thread.
02-21 17:30:49.863 I/Adreno-EGL(29642): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
02-21 17:30:49.863 I/Adreno-EGL(29642): OpenGL ES Shader Compiler Version: E031.29.00.00
02-21 17:30:49.863 I/Adreno-EGL(29642): Build Date: 04/04/16 Mon
02-21 17:30:49.863 I/Adreno-EGL(29642): Local Branch: mybranch19053788
02-21 17:30:49.863 I/Adreno-EGL(29642): Remote Branch: quic/LA.BF.1.1.3_rb1.12
02-21 17:30:49.863 I/Adreno-EGL(29642): Local Patches: NONE
02-21 17:30:49.863 I/Adreno-EGL(29642): Reconstruct Branch: NOTHING
02-21 17:30:49.889 I/OpenGLRenderer(29642): Initialized EGL, version 1.4
02-21 17:30:50.159 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:50.160 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:50.177 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.music/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10053
02-21 17:30:50.180 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.album/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10085
02-21 17:30:50.182 I/CastDatabase(5012): Opening the database
02-21 17:30:50.191 I/WifiManager(5012): Process gle.android.gms requested a scan
02-21 17:30:50.192 I/DiscoveryManager(5012): WifiGuestModeDeviceScanner enabled.
02-21 17:30:50.196 I/SQLiteCastStore(5012): 0 CastNetworkInfo instances loaded, 0 CastDeviceInfo instances loaded, 0 paired guest mode devices loaded.
02-21 17:30:50.201 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:50.201 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:50.359 I/ActivityManager(3520): Displayed com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity: +1s750ms (total +3s309ms)
02-21 17:30:50.359 I/Timeline(3520): Timeline: Activity_windows_visible id: ActivityRecord{b464bb1 u0 com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity t731} time:4997321
02-21 17:30:50.360 E/YouTube (29642): InteractionLoggingScreen is null.
02-21 17:30:50.395 W/CastMediaRouteProvider(5012): Not a Cast compatible category: MDX_MEDIA_ROUTE_CONTROL_CATEGORY
02-21 17:30:50.395 W/CastMediaRouteProvider(5012): Not a Cast compatible category: android.media.intent.category.LIVE_AUDIO
02-21 17:30:50.397 I/DiscoveryManager(5012): Filter criteria(233637DE) scannerFlags(2)
02-21 17:30:50.425 I/WifiManager(5012): Process gle.android.gms requested a scan
02-21 17:30:50.636 I/tad     (198): MiscTA Unit 66670: 
02-21 17:30:50.636 I/tad     (198): NOT WRITTEN (Identical)
02-21 17:30:50.636 I/tad     (198): MiscTA: Write of unit 66670 completed - OK
02-21 17:30:51.236 I/Timeline(29642): Timeline: Activity_idle id: android.os.BinderProxy@7b2803f time:4998199
02-21 17:30:51.261 I/art     (29642): Rejecting re-init on previously-failed class java.lang.Class<pqz>
02-21 17:30:51.262 I/art     (29642): Rejecting re-init on previously-failed class java.lang.Class<pqz>
02-21 17:30:51.262 I/art     (29642): Rejecting re-init on previously-failed class java.lang.Class<pqz>
02-21 17:30:52.387 I/Gobi    (733): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
02-21 17:30:52.388 I/Gobi    (733): vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1550: Failed to get TransState, rc 9
02-21 17:30:52.388 I/Gobi    (733): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
02-21 17:30:52.388 I/Gobi    (733): vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:2500: GetTransState() EBADF
02-21 17:30:53.634 E/AndroidRuntime(29642): FATAL EXCEPTION: AsyncTask #4
02-21 17:30:53.634 E/AndroidRuntime(29642): Process: com.google.android.youtube, PID: 29642
02-21 17:30:53.634 E/AndroidRuntime(29642): java.lang.RuntimeException: An error occurred while executing doInBackground()
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.lang.Thread.run(Thread.java:818)
02-21 17:30:53.634 E/AndroidRuntime(29642): Caused by: java.lang.ClassCastException: amcr cannot be cast to javax.net.ssl.HttpsURLConnection
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:266)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at com.pyler.youtubebackgroundplayback.YouTubeBackgroundPlayback$HooksDownloadTask.doInBackground(YouTubeBackgroundPlayback.java:253)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-21 17:30:53.634 E/AndroidRuntime(29642): 	... 4 more
02-21 17:30:53.638 D/ActivityManager(3520): New dropbox entry: com.google.android.youtube, system_app_crash, 398b0313-c67b-4711-9d90-8885dc7ba23a
02-21 17:30:53.639 W/ActivityManager(3520):   Force finishing activity com.google.android.youtube/com.google.android.apps.youtube.app.WatchWhileActivity
02-21 17:30:53.704 W/ContextImpl(21785): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1271 android.content.ContextWrapper.bindService:604 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192 
02-21 17:30:53.732 I/OpenGLRenderer(3520): Initialized EGL, version 1.4
02-21 17:30:53.778 I/art     (3520): Background partial concurrent mark sweep GC freed 27634(1909KB) AllocSpace objects, 4(80KB) LOS objects, 26% free, 43MB/59MB, paused 2.918ms total 117.508ms
02-21 17:30:53.815 I/Timeline(5294): Timeline: Activity_idle id: android.os.BinderProxy@77f5355 time:5000778
02-21 17:30:53.816 W/YouTube (29642): CsiAction [cnv] already ticked pl_int. Ignored.
02-21 17:30:53.888 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.music/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10053
02-21 17:30:53.889 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.album/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10085
02-21 17:30:53.889 W/CastMediaRouteProvider(5012): Not a Cast compatible category: MDX_MEDIA_ROUTE_CONTROL_CATEGORY
02-21 17:30:53.889 W/CastMediaRouteProvider(5012): Not a Cast compatible category: android.media.intent.category.LIVE_AUDIO
02-21 17:30:53.889 W/DiscoveryManager(5012): BroadcastReceiver is already registered
02-21 17:30:53.890 I/DiscoveryManager(5012): Filter criteria(233637DE) scannerFlags(2)
02-21 17:30:53.919 I/tad     (198): MiscTA Unit 10010: 
02-21 17:30:53.919 I/tad     (198): WRITTEN (Size 10)
02-21 17:30:53.944 I/Timeline(3520): Timeline: Activity_windows_visible id: ActivityRecord{a934768 u0 com.teslacoilsw.launcher/.NovaLauncher t657} time:5000906
02-21 17:30:53.957 I/tad     (198): Actual erase/write to flash done (count 43, time 1519230653).
02-21 17:30:53.957 I/tad     (198): MiscTA: Write of unit 10010 completed - OK
02-21 17:30:53.965 I/tad     (198): MiscTA Unit 10006: 
02-21 17:30:53.965 I/tad     (198): WRITTEN (Size 849)
02-21 17:30:53.981 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.music/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10053
02-21 17:30:53.981 W/ActivityManager(3520): Permission Denial: Accessing service ComponentInfo{com.sonyericsson.album/com.sonymobile.somcmediarouter.provider.dlna.DlnaMediaRouteProviderService} from pid=29642, uid=10189 that is not exported from uid 10085
02-21 17:30:53.982 W/DiscoveryManager(5012): BroadcastReceiver is already registered
02-21 17:30:53.982 I/DiscoveryManager(5012): Filter criteria(233637DE) scannerFlags(2)
02-21 17:30:54.009 I/tad     (198): Actual erase/write to flash done (count 44, time 1519230654).
02-21 17:30:54.009 I/tad     (198): MiscTA: Write of unit 10006 completed - OK
02-21 17:30:54.295 I/DiscoveryManager(5012): Filter criteria(null) scannerFlags(0)
02-21 17:30:55.651 I/Process (29642): Sending signal. PID: 29642 SIG: 9
02-21 17:30:55.720 D/GraphicsStats(3520): Buffer count: 8
02-21 17:30:55.720 D/ConnectivityService(3520): ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=88, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@12f8489)
02-21 17:30:55.721 D/ConnectivityService(3520): releasing NetworkRequest NetworkRequest [ id=88, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
02-21 17:30:55.724 E/ConnectivityService(3520): RemoteException caught trying to send a callback msg for NetworkRequest [ id=88, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
02-21 17:30:55.773 I/ActivityManager(3520): Process com.google.android.youtube (pid 29642) has died
02-21 17:30:55.839 W/AppOps  (3520): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
02-21 17:30:56.538 I/ActivityManager(3520): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10076 on display 0
02-21 17:30:56.652 I/Timeline(4443): Timeline: Activity_idle id: android.os.BinderProxy@7cad8c9 time:5003615
02-21 17:30:56.711 I/Timeline(3520): Timeline: Activity_windows_visible id: ActivityRecord{f20a66f u0 com.android.systemui/.recents.RecentsActivity t660} time:5003673
02-21 17:30:57.998 I/Timeline(29360): Timeline: Activity_idle id: android.os.BinderProxy@94349f9 time:5004960
02-21 17:30:58.180 I/Timeline(3520): Timeline: Activity_windows_visible id: ActivityRecord{7d546f0 u0 com.pluscubed.matlog/com.pluscubed.logcat.ui.LogcatActivity t730} time:5005143
