### ISSUE TITLE
newest update still needs the hook

### ISSUE THREAD

**Issue by dariendark** [wanam/YouTubeAdAway#64]
I'm sure a few others have already mentioned this to you. But we are getting the voting cards with the Newest YouTube Exposed update. Personally I just backtracked to the previous version for now. Best of luck with this amazing application. Thank you

**Comment by wanam** [comment]
Please post a screenshot + your xposed logs.

**Comment by wanam** [comment]
Closed for lake of response.
If the issue persists, feel free to re-open it, and post a screenshot + your xposed logs.
