### ISSUE TITLE
Salam

### ISSUE THREAD

**Issue by zabhisaeed** [wanam/YouTubeAdAway#66]
I need debug version 4.3.1

**Comment by wanam** [comment]
Why do you need to debug an old version?

**Comment by zabhisaeed** [comment]
m working on adfree youtube without xposed

i have successfully managed to hide Ad card in Smali ( play store suggestions) but unfortunately some times i get Visit advertisers ads after playing 12 to 15 videos .

i need clue :)

**Comment by zabhisaeed** [comment]
version 4.3.2
