### ISSUE TITLE
YouTube keeps stopping 

### ISSUE THREAD

**Issue by JSaunders97** [wanam/YouTubeAdAway#70]
[xposed_error_20180413_104613.log](https://github.com/wanam/YouTubeAdAway/files/1907164/xposed_error_20180413_104613.log)
YouTube closes shortly after open every time I open it, the issue stops when I deactivate YouTubeAdAway.

**Comment by wanam** [comment]
Duplicate of https://github.com/wanam/YouTubeAdAway/issues/60
