### ISSUE TITLE
Option for non rooted phones?

### ISSUE THREAD

**Issue by TheBaronJJ** [wanam/YouTubeAdAway#73]
Hi, is there a way to use this app for non rooted phones? Such as using adb and giving 
ma.wanam.youtubeadaway_v432_1afe62.apk admin privileges. If so please message back

**Comment by wanam** [comment]
Sorry no, it's not a matter of permission, it needs to alter code on
runtime.

**Comment by TheBaronJJ** [comment]
Is there any other way to use your ad blocker without root, and if so can
you please tell me.

**Comment by wanam** [comment]
Sorry no.

**Comment by TheBaronJJ** [comment]
Is there any other way that would be great for a non rooted phone to have
no adverts on youtube. Without having a vpn?

**Comment by B2Pi** [comment]
https://forum.xda-developers.com/android/apps-games/app-youtube-vanced-edition-t3758757
