### ISSUE TITLE
Youtube crash

### ISSUE THREAD

**Issue by Skorpion96** [wanam/YouTubeAdAway#77]
Youtube crash with youtube adaway activated.
Log:05-28 16:53:46.184 I/Xposed  (  327): -----------------
05-28 16:53:46.184 I/Xposed  (  327): Starting Xposed version 90-beta3, compiled for SDK 27
05-28 16:53:46.184 I/Xposed  (  327): Device: Nexus 5 (LGE), Android version 8.1.0 (SDK 27)
05-28 16:53:46.184 I/Xposed  (  327): ROM: ua_hammerhead-userdebug 8.1.0 OPM2.171019.029 2172 test-keys
05-28 16:53:46.184 I/Xposed  (  327): Build fingerprint: google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys
05-28 16:53:46.184 I/Xposed  (  327): Platform: armeabi-v7a, 32-bit binary, system server: yes
05-28 16:53:46.184 I/Xposed  (  327): SELinux enabled: yes, enforcing: no
05-28 16:53:48.338 I/Xposed  (  327): -----------------
05-28 16:53:48.339 I/Xposed  (  327): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-28 16:53:50.656 I/Xposed  (  327): Detected ART runtime
05-28 16:53:50.661 I/Xposed  (  327): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
05-28 16:53:51.262 I/Xposed  (  327): Loading modules from /data/app/ma.wanam.youtubeadaway-trOjDpcDAnScABerOkYOBg==/base.apk
05-28 16:53:51.283 I/Xposed  (  327):   Loading class ma.wanam.youtubeadaway.Xposed

**Comment by JackChen007** [comment]
Me too. Maybe Youtube has detected that you have installed xposed youtubeadaway.
