### ISSUE TITLE
After the last update some ads started to appear.

### ISSUE THREAD

**Issue by BlackGhost12** [wanam/YouTubeAdAway#8]
![screenshot_2017-05-05-19-51-08](https://cloud.githubusercontent.com/assets/19236621/25755613/55dfab2e-31cc-11e7-9c67-92310a0e778c.png)

**Comment by BlackGhost12** [comment]
I started to encounter this problem in the last two updates of Youtube. Xposed v87. Android 5.1.1. Exisztenz Premium v7 Rom.

**Comment by rambomhtri** [comment]
These ad cards are a new "feature" of the latest YouTube versions, I guess AdAway needs to be updated to address and remove them.
