### ISSUE TITLE
Ads are back with youtube 13.30.56

### ISSUE THREAD

**Issue by skrilin5** [wanam/YouTubeAdAway#88]
Hi Wanam,

The ads are back using youtube version 13.30.56.
Enclosed the xposed log.

Thanks

[xposed_error_20180809_165016 - Copy.log](https://github.com/wanam/YouTubeAdAway/files/2276319/xposed_error_20180809_165016.-.Copy.log)

**Comment by ngosang** [comment]
@wanam we need you!!!

**Comment by wanam** [comment]
It's been a while I didn't use Xposed, according to the logs it should be easy to fix, i guess it's related to a proguard map change.
Unfortunately i don't have time to Root and install it on my device right now, anyone else can use my sources to debug and find out what changed.

**Comment by moralrebuild** [comment]
Anyone can take this honor fixing task?

**Comment by ChristophPech** [comment]
@wanam I fixed it. I generalized the brute force detection so it doesn't matter if proguard renames anything. It's name agnostic now.

**Comment by tgc12** [comment]
You are the boss
