### ISSUE TITLE
You tube adaway

### ISSUE THREAD

**Issue by nemsis72** [wanam/YouTubeAdAway#89]
AdAway not working on current you tube app version 13.30.56.
Xpose module has no affect on ads.
Using oneplus3t Android 8.0 oreo. Rooted, and xposed framework version 90-Beta3 installed.

**Comment by NopeDK** [comment]
Sam here, Nexus 5 , 6.0 AOSP, rooted, Franco Kernel, Xposed 89

**Comment by hsinankirdar** [comment]
Same here note 5 nougat 7.0
