### ISSUE TITLE
Ads have returned for me. 

### ISSUE THREAD

**Issue by Radioplayer1997** [wanam/YouTubeAdAway#9]
Youtube 12.16.56, latest ad away, latest youtube ad away, latest xposed script. I'm getting a lot of ads now.

**Comment by rambomhtri** [comment]
Try reinstalling everything you can, I'm using latest versions of AdAway, YouTube and Xposed in Marshmallow 6.0.1 and I'm not getting any ads, only those new ad cards below videos.

**Comment by Grossdm** [comment]
@Radioplayer1997 Just to clarify, what do you mean by "latest xposed script"?
Perhaps you're just referring to YouTubeAdAway but if not, I'm missing something in my setup.
TIA,
Doug®

**Comment by Radioplayer1997** [comment]
@Grossdm actually I've updated too resurrection remix 7.1.2, and I now use a magisk module for youtube ad blocker. Works amazingly

And the "script" I mentioned was meaning the latest xposed script you could download and flash onto your system.

**Comment by Grossdm** [comment]
@Radioplayer1997 Thanks for the info and the quick reply!
