### ISSUE TITLE
Youtube crashes 90% times. Restart doesn't help

### ISSUE THREAD

**Issue by dagaabhijeet** [wanam/YouTubeAdAway#95]
08-30 18:34:10.501 I/Xposed  (30566): YouTube AdAway: brute force failed!
08-30 18:35:11.467 I/Xposed  (30985): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:35:18.545 I/Xposed  (30985): YouTube AdAway: brute force failed!
08-30 18:35:52.841 I/Xposed  (31163): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:35:59.768 I/Xposed  (31163): YouTube AdAway: brute force failed!
08-30 18:36:55.272 I/Xposed  (31629): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:37:02.672 I/Xposed  (31629): YouTube AdAway: brute force failed!
08-30 18:37:34.143 I/Xposed  (31801): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:37:41.182 I/Xposed  (31801): YouTube AdAway: brute force failed!
08-30 18:39:12.827 I/Xposed  (32282): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:39:20.907 I/Xposed  (32282): YouTube AdAway: brute force failed!
08-30 18:40:45.774 I/Xposed  (32466): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:40:53.510 I/Xposed  (32466): YouTube AdAway: brute force failed!
08-30 18:42:13.972 I/Xposed  (32639): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:42:21.491 I/Xposed  (32639): YouTube AdAway: brute force failed!
08-30 18:44:05.221 I/Xposed  (  587): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:44:12.869 I/Xposed  (  587): YouTube AdAway: brute force failed!
08-30 18:46:25.221 I/Xposed  ( 1160): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:46:32.912 I/Xposed  ( 1160): YouTube AdAway: brute force failed!
08-30 18:47:41.060 I/Xposed  ( 1467): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:47:49.100 I/Xposed  ( 1467): YouTube AdAway: brute force failed!
08-30 18:49:33.382 I/Xposed  ( 1746): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:49:40.984 I/Xposed  ( 1746): YouTube AdAway: brute force failed!
08-30 18:49:47.807 I/Xposed  ( 9828): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:49:49.661 I/Xposed  ( 9828): YouTube AdAway: brute force failed!
08-30 18:49:51.843 I/Xposed  ( 2353): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:49:54.967 I/Xposed  ( 2353): YouTube AdAway: brute force failed!
08-30 18:49:59.612 I/Xposed  ( 2590): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:50:06.296 I/Xposed  ( 2590): YouTube AdAway: brute force failed!
08-30 18:50:46.428 I/Xposed  ( 2716): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:50:53.478 I/Xposed  ( 2716): YouTube AdAway: brute force failed!
08-30 18:51:16.682 I/Xposed  ( 3111): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:51:23.788 I/Xposed  ( 3111): YouTube AdAway: brute force failed!
08-30 18:52:12.116 I/Xposed  ( 3321): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:52:19.477 I/Xposed  ( 3321): YouTube AdAway: brute force failed!
08-30 18:53:00.190 I/Xposed  ( 3680): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.2
08-30 18:53:06.991 I/Xposed  ( 3680): YouTube AdAway: b

**Comment by SandPox** [comment]
Clear data of youtube app and it won't crash again, it will crash again if you reboot/close the youtube app via tasklist
