### ISSUE TITLE
YouTube keep crashing

### ISSUE THREAD

**Issue by ZFranz** [wanam/YouTubeAdAway#96]
After updating the module to 4.3.3, whenever i try to launch YouTube it crashes. Here is the log

12-14 23:51:02.874 I/Xposed  (  693): -----------------
12-14 23:51:02.874 I/Xposed  (  693): Starting Xposed version 90-beta3, compiled for SDK 27
12-14 23:51:02.874 I/Xposed  (  693): Device: ONEPLUS A5000 (OnePlus), Android version 8.1.0 (SDK 27)
12-14 23:51:02.874 I/Xposed  (  693): ROM: ONEPLUS A5000_23_180808
12-14 23:51:02.874 I/Xposed  (  693): Build fingerprint: OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/1808081927:user/release-keys
12-14 23:51:02.874 I/Xposed  (  693): Platform: arm64-v8a, 64-bit binary, system server: yes
12-14 23:51:02.874 I/Xposed  (  693): SELinux enabled: yes, enforcing: yes
12-14 23:51:02.887 I/Xposed  (  693): -----------------
12-14 23:51:02.887 I/Xposed  (  693): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-01 12:42:25.633 I/Xposed  (  693): Detected ART runtime
09-01 12:42:25.635 I/Xposed  (  693): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-01 12:42:25.908 I/Xposed  (  693): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.COIN-i_S9a_5v_R8FypRZg0EhNw==/base.apk
09-01 12:42:26.014 I/Xposed  (  693):   Loading class com.chelpus.XSupport
09-01 12:42:26.025 I/Xposed  (  693): Loading modules from /data/app/com.oasisfeng.greenify-_Kyd2qxoWwCeW3G3eIluzg==/base.apk
09-01 12:42:26.128 I/Xposed  (  693):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
09-01 12:42:26.134 I/Xposed  (  693):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
09-01 12:42:26.134 I/Xposed  (  693): Loading modules from /data/app/ma.wanam.youtubeadaway-N_LXNY_BCI_gJYa7KB6kMg==/base.apk
09-01 12:42:26.141 I/Xposed  (  693):   Loading class ma.wanam.youtubeadaway.Xposed
09-01 12:42:34.113 I/Xposed  (  694): -----------------
09-01 12:42:34.113 I/Xposed  (  694): Starting Xposed version 90-beta3, compiled for SDK 27
09-01 12:42:34.113 I/Xposed  (  694): Device: ONEPLUS A5000 (OnePlus), Android version 8.1.0 (SDK 27)
09-01 12:42:34.113 I/Xposed  (  694): ROM: ONEPLUS A5000_23_180808
09-01 12:42:34.113 I/Xposed  (  694): Build fingerprint: OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/1808081927:user/release-keys
09-01 12:42:34.113 I/Xposed  (  694): Platform: arm64-v8a, 32-bit binary, system server: no
09-01 12:42:34.113 I/Xposed  (  694): SELinux enabled: yes, enforcing: yes
09-01 12:42:34.115 I/Xposed  (  694): -----------------
09-01 12:42:34.115 I/Xposed  (  694): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-01 12:42:34.701 I/Xposed  (  694): Detected ART runtime
09-01 12:42:34.704 I/Xposed  (  694): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-01 12:42:34.898 I/Xposed  (  694): Loading modules from /data/app/com.android.vending.billing.InAppBillingService.COIN-i_S9a_5v_R8FypRZg0EhNw==/base.apk
09-01 12:42:34.997 I/Xposed  (  694):   Loading class com.chelpus.XSupport
09-01 12:42:35.013 I/Xposed  (  694): Loading modules from /data/app/com.oasisfeng.greenify-_Kyd2qxoWwCeW3G3eIluzg==/base.apk
09-01 12:42:35.101 I/Xposed  (  694):   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
09-01 12:42:35.111 I/Xposed  (  694):   Loading class com.oasisfeng.greenify.pro.SettingsPatch
09-01 12:42:35.111 I/Xposed  (  694): Loading modules from /data/app/ma.wanam.youtubeadaway-N_LXNY_BCI_gJYa7KB6kMg==/base.apk
09-01 12:42:35.204 I/Xposed  (  694):   Loading class ma.wanam.youtubeadaway.Xposed
09-01 12:43:12.317 I/Xposed  ( 7439): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
09-01 12:43:12.813 I/Xposed  ( 7439): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
09-01 12:43:14.728 I/Xposed  ( 7818): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
09-01 12:43:27.500 I/Xposed  (10179): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
09-01 12:46:24.040 I/Xposed  (15120): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3
09-01 12:46:29.930 I/Xposed  (15500): YouTube: com.google.android.youtube 13.34.50 loaded with module version 4.3.3

**Comment by zhuhang-jasper** [comment]
+1

**Comment by daktah** [comment]
Same, as soon as I boot with the module on it crashes and won't open, with it off it's perfectly fine
